// Script to add specific missing book mappings
import fs from 'fs';

// Read the current mapping file
const mappingContent = fs.readFileSync('src/utils/bookCoverMapping.ts', 'utf8');

// Find the position to insert new mappings (before the closing brace)
const closingBraceIndex = mappingContent.lastIndexOf('}');
const beforeClosingBrace = mappingContent.substring(0, closingBraceIndex);
const afterClosingBrace = mappingContent.substring(closingBraceIndex);

// Missing mappings to add
const missingMappings = [
  '  "10 Books in 1": "/BookCoversNew/Ten books in one.png"',
  '  "10 Ways to Write More Effective Ads": "/BookCoversNew/10 ways to write effective ads.png"',
  '  "12Th Fail Hindi Novel": "/BookCoversNew/12th Fail.png"',
  '  "A Day in the Life": "/BookCoversNew/A Day In The Life Robert Greenfield.jpeg"',
  '  "A Text Book of Dravyaguna Vijnana": "/BookCoversNew/a textbook of dravyaguna.jpg"',
  '  "Adventures of Huckleberry Finn": "/BookCoversNew/adventures of huckleberry fins.jpg"',
  '  "Akbar And Birbal": "/BookCoversNew/Akbar Aur Birbal.jpeg"',
  '  "Allen B Tucker Computer Science and Engineering Handbook": "/BookCoversNew/second edition computer science handbook.jpg"',
  '  "American Folk Tales": "/BookCoversNew/american folktales.jpg"',
  '  "Angels Demons": "/BookCoversNew/Angels and demons.png"',
  '  "Ayurveda Treatment for Beginner": "/BookCoversNew/Ayurveda Divine Science Of Life.jpg"',
  '  "Biography of Charlie Chaplin": "/BookCoversNew/Charlie Chaplin S Biography.png"',
  '  "Biography of Swami Vivekananda": "/BookCoversNew/Swami vivekananda biography.png"',
  '  "Buddhas Brain The Practical Neuroscience": "/BookCoversNew/Buddha S Brain.jpg"',
  '  "Complete Sherlock Holmes 1960": "/BookCoversNew/Sir Arthur Conan Doyle Complete.jpeg"',
  '  "Dear God What s Happening to Us": "/BookCoversNew/Lynn Grabhorn Dear God What S Happening To Us.jpeg"',
  '  "Do Bailo Ki Katha": "/BookCoversNew/DO Kadam Aur Sahi.png"',
  '  "Drawing Cartoons and Comics for Dummies PDF": "/BookCoversNew/drawing cartoons and comics for dummies.jpg"',
  '  "Elmer s Friends": "/BookCoversNew/elmers friend.jpg"',
  '  "Elmers s Special Day": "/BookCoversNew/elmers special day.jpg"',
  '  "Emotional Intelligence": "/BookCoversNew/Emotional Intelligence.jpg"',
  '  "Essentials of Medical Microbiology": "/BookCoversNew/Essentials of Microbiology.png"',
  '  "Five Point Someone": "/BookCoversNew/5 points someone what not to do at iit.jpg"',
  '  "Frankenstein or The Mordern Prometheus": "/BookCoversNew/Frankstein.png"',
  '  "Fundamental Theories of Physics": "/BookCoversBlack Hole Physics.jpg"',
  '  "Guide to Competetive Programming": "/BookCoversNew/Allen B Tucker Computer Science and Engineering Handbook.pdf"',
  '  "Harry Potter and the Philosophers Stone": "/BookCoversNew/harry-potter-1-philosophers-stone.png"',
  '  "Harry Potter and the Prisoner of Azkaban": "/BookCoversNew/harry-potter-3-prisoner-of-azkaban.png"',
  '  "Harry Potter and the Goblet of FIre": "/BookCoversNew/harry-potter-4-goblet-of-fire.png"',
  '  "Harry Potter and the Order of the Phoenix": "/BookCoversNew/harry-potter-5-order-of-phoenix.png"',
  '  "Harry Potter and the Half Blood Prince": "/BookCoversNew/harry-potter-6-half-blood-prince.png"',
  '  "Harry Potter and the Deathly Hallows": "/BookCoversNew/harry-potter-7-deathly-hallows.png"',
  '  "Harry Potter and the Cursed Child": "/BookCoversNew/harry-potter-8-cursed-child.png"',
  '  "Harry Potter Complete Collection": "/BookCoversNew/Harry Potter Complete Collection.jpg"',
  '  "Healing Depression The Mind Body Way": "/BookCoversNew/healing depression the mind body way.jpg"',
  '  "Henry and Mudge and Annie Good Move": "/BookCoversNew/Henry And Mudge And Annie S Good Move.png"',
  '  "Henry and Mudge and Annie Perfect Pet": "/BookCoversNew/Henry And Mudge Annie S Perfect Pet.png"',
  '  "Henry and Mudge and Mrs Hopper House": "/BookCoversNew/Henry And Mudge Mr Hopper S House.png"',
  '  "Henry and Mudge and the Bedtime Thumps": "/BookCoversNew/Henry and Mudge and the bedtime thums.png"',
  '  "Henry and Mudge and the Big Sleepover": "/BookCoversNew/Henry and Mudge and a big sleepover.png"',
  '  "Henry and Mudge and the Great Grandpas": "/BookCoversNew/Henry and Mudge and the great grandpa.png"',
  '  "Henry and Mudge and the Sneaky Crackers": "/BookCoversNew/Henry and Mudge and sneaky crackers.png"',
  '  "Henry and Mudge and the Starry Night May": "/BookCoversNew/Henry and Mudge and the starry night.png"',
  '  "Henry and Mudge and the Wild Goose Chase": "/BookCoversNew/Henry and Mudge and the wild goose.png"',
  '  "Henry and Mudge Get the Cold Shivers": "/BookCoversNew/Henry and Mudge and the cold shivers.png"',
  '  "Henry and Mudge in the Family Trees": "/BookCoversNew/Henry and Mudge in the green time.png"',
  '  "Henry and Mudge The First Book of Their Adventures": "/BookCoversNew/Henry and Mudge the first book.png"',
  '  "Hotel by Arthur Hailey": "/BookCoversNew/hotel.jpg"',
  '  "How I Topped The UPSC and How You Can Too": "/BookCoversNew/how I topped the upsc.jpg"',
  '  "How to Talk to Anyone 92 Little Tricks for Big Success": "/BookCoversNew/How To Talk To Anyone 92 Trick.jpg"',
  '  "If It s Not Forever": "/BookCoversNew/If It S Not Forever, It S Not Love.jpg"',
  '  "It s Not How Good You Are It s How Good You Want to Be": "/BookCoversNew/It S Not How Good You Are, It S How Good You Want To Be.jpg"',
  '  "Its All In The Planets": "/BookCoversNew/It S All In The Planets.png"',
  '  "Julius Caesar The Colossus of Rome": "/BookCoversNew/the colossus of rome.jpg"',
  '  "Konark Hindi Novel": "/BookCoversNew/Konark.png"',
  '  "Legal Eagles Stories of the Top Seven Indian Lawyers": "/BookCoversNew/legal eagles.jpg"',
  '  "Life is a Soap Bubble": "/BookCoversNew/Life of A Soap Bubble.png"',
  '  "Lord Of The Rings The Return Of The King": "/BookCoversNew/The Lord Of The Rings 1.jpeg"',
  '  "Losing My Virginity and Other Dumb Ideas": "/BookCoversNew/Losing My Virginity And All Other Dares.jpeg"',
  '  "love facebook": "/BookCoversNew/Love@facebook.jpeg"',
  '  "Mahabharat": "/BookCoversNew/Mahabharat Hindi.jpeg"',
  '  "Mahabharata Veda Vyasa eng": "/BookCoversNew/Mahabharat Ved Vyas.jpeg"',
  '  "Mahayoddha Kalki Sword of Shiva": "/BookCoversNew/Mahayoddha Kalki Sword Of Shiva.jpeg"',
  '  "Marry Poppins": "/BookCoversNew/Mary poppins 1967.jpeg"',
  '  "Microprocessors Microcontroller Systems": "/BookCoversNew/microprocessor and microcontroller system.jpg"',
  '  "Mother Teresa A Biography": "/BookCoversNew/Mother Teresa A Biography.jpeg"',
  '  "My Clingy Girlfriend": "/BookCoversNew/My Clingy Girlfriend Madhuri.jpeg"',
  '  "Napoleon A Biography": "/BookCoversNew/Napolean A Biography.jpeg"',
  '  "Now That You are Rich": "/BookCoversNew/You Are Trending In My Dreams Now.jpeg"',
  '  "Oh Yes I m Single": "/BookCoversNew/Oh Yes I M Single, And So Is My Girlfriend.jpg"',
  '  "One Hundred Years Of Solitude": "/BookCoversNew/One Hundred Years Of Soltitude.jpeg"',
  '  "One Indian Girl": "/BookCoversNew/Gone Girl.jpg"',
  '  "Our Story Needs No Filter": "/BookCoversNew/Our Story Needs No Filter Sudeep.jpeg"',
  '  "Outsiders American Short Stories for students of ESL": "/BookCoversNew/Outsiders American Short Stories for students of esl.jpeg"',
  '  "Percy Jackson and The Battle of the Labyrinth": "/BookCoversNew/Percy Jackson And The Battle Of The Labyrimin.jpeg"',
  '  "Picture Dictionary": "/BookCoversNew/Picture Dictionary Longman Children.jpeg"',
  '  "Prem Purana Mythological Love Stories": "/BookCoversNew/Prem Purana Mythological Love Stories.jpeg"',
  '  "Presentation Secrets Of Steve Jobs": "/BookCoversNew/Presentation Secets Of Steve Jobs.jpeg"',
  '  "Python API Development Fundamentals": "/BookCoversNew/Python API Deevelopment Fundamentals.jpeg"',
  '  "Reasons to Stay Alive": "/BookCoversNew/Reasons To Stay Alive Matt Haig.jpeg"',
  '  "Reconsidering REDD Authority Power and Law": "/BookCoversNew/Reconsidering Redd+ Authority Ananya Sharma.jpeg"',
  '  "Reflections Of A Man": "/BookCoversNew/Reflections Of A Man Amari Soul.jpeg"',
  '  "Religious Therapeutics": "/BookCoversNew/Religious Therapeutics Body.jpeg"',
  '  "Revolution 2020": "/BookCoversNew/Revolution 2020 Chetan Bhagat.jpeg"',
  '  "Rich Dads Increase Your Financial IQ Get Smarter with Your Money": "/BookCoversNew/Rich Dads Increase Your Financial IQ.jpeg"',
  '  "Right Here Right Now": "/BookCoversNew/Right Here Right Now Nikita Singh.jpeg"',
  '  "Ruk Jaana Nahin": "/BookCoversNew/Ruk Jaana Nahin Nishant Jain.jpeg"',
  '  "Sacred Games": "/BookCoversNew/Sacred Games A Novel.jpeg"',
  '  "Scion of Ikshvaku": "/BookCoversNew/Scian Of Ikshvaku Ram Chandra.jpeg"',
  '  "Self Liberation From Fear Worry and Angry": "/BookCoversNew/Self Liberation from Fear,Worry and Angry.png"',
  '  "She Broke Up I Didn t": "/BookCoversNew/She Broke Up. I Didn T.jpg"',
  '  "She Broke Up I Didn t I Just Kissed": "/BookCoversNew/She Broke Up I Didn T I Just Kissed.jpeg"',
  '  "She Broke Up I Didn t Just Du": "/BookCoversNew/She Broke Up I Didn T Just Du.jpeg"',
  '  "Short Stories for Children for Spoken English": "/BookCoversNew/Short Stories For Children For Spoken English Practice.jpeg"',
  '  "Short Stories of The Day": "/BookCoversNew/The Complete Short Stories.jpeg"',
  '  "Short-Stories": "/BookCoversNew/stories.jpeg"',
  '  "Shri Ramcharitmanas Hindi": "/BookCoversNew/Shri Ramcharitramanas (Hindi).jpeg"',
  '  "Sri Ramcharitmanas English": "/BookCoversNew/Sri Ramcharitramanas English All Pages.jpeg"',
  '  "Steal the Show": "/BookCoversNew/how I topped the upsc.jpg"',
  '  "Stories From My Teacher": "/BookCoversNew/STORYCRAFT The Complete Guide to Storytelling.jpeg"',
  '  "Stories from PANCHATANTRA": "/BookCoversNew/Stories Of Panchatantra.jpeg"',
  '  "Story Craft": "/BookCoversNew/STORYCRAFT The Complete Guide to Storytelling.jpeg"',
  '  "Super Immunity": "/BookCoversNew/Super Immunity The Essential Nutrition.jpeg"',
  '  "Swadeshi Chikitsa": "/BookCoversNew/SwadeshiChikitsa Vol 1.jpeg"',
  '  "Tea for Two and a Piece of Cake": "/BookCoversNew/Tea For Two And A Piece Of Cake Sudeep Menon.jpeg"',
  '  "Tell The Last Breath": "/BookCoversNew/Till The Last Breath.jpeg"',
  '  "Thats The Way We Met": "/BookCoversNew/That S The Way We Meet N.jpeg"',
  '  "The 3 Three Mistakes of My Life": "/BookCoversNew/The Mistakes Of My Life.jpeg"',
  '  "The 5 Second Rule": "/BookCoversNew/Mel Robbins The 5 Second Rule.jpeg"',
  '  "The 5AM Club": "/BookCoversNew/The 5 Am Club Robin Sharma.jpeg"',
  '  "The adventures of Tom Sawyer": "/BookCoversNew/The adventures of Tom bombadil.png"',
  '  "The Alchemist": "/BookCoversNew/The Alchemist By Paulo Caelho.jpeg"',
  '  "The Anxiety and Phobia Workbook": "/BookCoversNew/The Anxiety And Phobia Workbook.jpeg"',
  '  "The Art of Public Speaking": "/BookCoversNew/The Art Of Public Speaking.png"',
  '  "The Bhagavad Gita": "/BookCoversNew/The Bhagavad Gita A Biography.jpeg"',
  '  "The Boy in The Striped Pajamas": "/BookCoversNew/The Boy In The Striped Pajamas.jpeg"',
  '  "The Boy with a Broken Heart": "/BookCoversNew/The Boy With A Broken Heart.jpeg"',
  '  "The Call of the Wild": "/BookCoversNew/The Call Of The Wild.jpeg"',
  '  "The Complete Short Stories": "/BookCoversNew/The Complete Short Stories.jpeg"',
  '  "The Count Of MonteCristo": "/BookCoversNew/The Count Of Monte Cristo.jpeg"',
  '  "The Courage to be Disliked": "/BookCoversNew/The Courage To Be Disliked.jpeg"',
  '  "The DaVinci Code": "/BookCoversNew/The Davinci Code Dan Brown.jpeg"',
  '  "The Day of the Jackal": "/BookCoversNew/The Day Of The Jackal.jpeg"',
  '  "The Extraordinary Miss Sunshine": "/BookCoversNew/The Extraordinary Miss Sunshine.jpeg"',
  '  "The Fisher Queens Dynasty": "/BookCoversNew/The Fisher Queens Dyansty.jpeg"',
  '  "The Forty Five Guardsmen": "/BookCoversNew/The Forty Five Guardsmen.jpeg"',
  '  "The Fox": "/BookCoversNew/The Fox Frederick Forysyth.jpeg"',
  '  "The Gifts of Imperfection": "/BookCoversNew/The Gifts Of Imperfection.jpeg"',
  '  "The Girl I Last Loved": "/BookCoversNew/The Girl I Last Loved Smita Kau.jpeg"',
  '  "The Girl in Room 105": "/BookCoversNew/The Girl In Room 105.jpeg"',
  '  "The Happiness Trap": "/BookCoversNew/The Happiness Trap.jpeg"',
  '  "The House That BJ Built": "/BookCoversNew/The House That BJ Built.jpeg"',
  '  "The Intelligent Investor": "/BookCoversNew/The Intelligent Investor.jpeg"',
  '  "The Jungle Book": "/BookCoversNew/The Jungle Book Nt.jpeg"',
  '  "The Kalam Effect": "/BookCoversNew/PM Nair The Kalam Effect.jpeg"',
  '  "The Little Mermaid": "/BookCoversNew/The Little Mermaid.jpeg"',
  '  "The Lord of the Rings The Fellowship of the Ring": "/BookCoversNew/The Lord Of The Rings 1.jpeg"',
  '  "The Lord of the Rings The Return of the King": "/BookCoversNew/The Lord Of The Rings 3.jpeg"',
  '  "The Lord of the Rings The Two Towers": "/BookCoversNew/The Lord Of The Rings 2.jpeg"',
  '  "The Lost Symbol": "/BookCoversNew/The Lost Symbol.jpeg"',
  '  "The Man Who Saved India": "/BookCoversNew/The Man Who Saved India SARDAR PATEL.jpeg"',
  '  "The Merry Adventures of Robin Hood": "/BookCoversNew/The Merry Adventures Of Robin Hood.jpeg"',
  '  "The Monk who Sold His Ferrari": "/BookCoversNew/The Monk Who Sold His Ferrari Robin S Sharma.jpeg"',
  '  "The Mother I Never Knew": "/BookCoversNew/The Mother I Never Knew.jpeg"',
  '  "The ONE YOU CANNOT HAVE": "/BookCoversNew/The One You Cannot Have.jpeg"',
  '  "The Palace of Illusions": "/BookCoversNew/The Palace Of Illusions.jpeg"',
  '  "The Paradoxical Prime Minister": "/BookCoversNew/The Paradoxical Prime Minister.jpeg"',
  '  "The Pilgrimage": "/BookCoversNew/The Pilgrimage.jpeg"',
  '  "The Promise": "/BookCoversNew/The Promise Nikita Singh.jpeg"',
  '  "The Psychology of Money": "/BookCoversNew/Morgan Housel Psychology of Money.jpeg"',
  '  "The Road Less Traveled": "/BookCoversNew/The Road Less Travelled.jpeg"',
  '  "The Science of Self Healing": "/BookCoversNew/The Science Of Self Healing.jpeg"',
  '  "The Secret": "/BookCoversNew/The Secret.jpeg"',
  '  "The Secret Wish List": "/BookCoversNew/The Secret Wish List.jpeg"',
  '  "The Secret Wishlist": "/BookCoversNew/The Secret Wishlist Preeti Shenoy.jpeg"',
  '  "The Silent Patient by Alex Michaelides": "/BookCoversNew/The Silent Patient.jpeg"',
  '  "The Three Body Problem": "/BookCoversNew/The Three Body Problem.png"',
  '  "The Three Musketeers": "/BookCoversNew/THE THREE MUSKETERS.jpeg"',
  '  "The Wheel of Time": "/BookCoversNew/The Wheel Of Time.jpeg"',
  '  "The Worlds Best Boyfriend": "/BookCoversNew/The World S Best Boyfriend.jpeg"',
  '  "The Zoya Factor": "/BookCoversNew/The Zoya Factor.jpeg"',
  '  "The adventures of Tom Sawyer": "/BookCoversNew/The adventures of Tom bombadil.png"',
  '  "The colossus of rome": "/BookCoversNew/the colossus of rome.jpg"',
  '  "The ritual": "/BookCoversNew/the ritual.jpg"',
  '  "The way of the superior man": "/BookCoversNew/the way of the superior man.jpg"',
  '  "Think Like A Monk": "/BookCoversNew/think like a monk.jpg"',
  '  "Three Mistakes of My Life": "/BookCoversNew/The Mistakes Of My Life.jpeg"',
  '  "Time Stops At Shamli Other Stories": "/BookCoversNew/Time Stops At Shamli.jpeg"',
  '  "Trading Price Action": "/BookCoversNew/Trading Price Action Trading Ranges.jpeg"',
  '  "Very Hungry Caterpillar": "/BookCoversNew/Very Hungry Cterpillar.jpeg"',
  '  "Vladimir Nabokov Lolita": "/BookCoversNew/Vladmir Nabokov Lolita Penguin Modern Classics.jpeg"',
  '  "Wabi Sabi Japanese Wisdom for a Perfectly Imperfect Life": "/BookCoversNew/Wabi Sabi Japanese Wisdom For A Perfectly Imperfect Life.jpeg"',
  '  "When Bad Things Happen to Good People": "/BookCoversNew/When Bad Things Happens To Good People.jpeg"',
  '  "When Dimple Met Rishi": "/BookCoversNew/When Dimple Met Rishi.jpeg"',
  '  "When Only Love Remains": "/BookCoversNew/When Only Love Remains -Durjoy Datta .jpeg"',
  '  "Will You Still Love Me": "/BookCoversNew/Will You Still Love Me Ravindra Singh.jpeg"',
  '  "Wings Of Fire": "/BookCoversNew/wings of fire.jpg"',
  '  "Wonder": "/BookCoversNew/Wonder.jpeg"',
  '  "World s Best Boyfriend": "/BookCoversNew/World S Best Boyfriend.jpg"',
  '  "You are the Best Wife A True Love Story": "/BookCoversNew/You Are The Best Wife.jpeg"',
  '  "You are the Password of My Life": "/BookCoversNew/You Re The Password Of My Life.jpeg"',
  '  "You are Trending in my Dreams": "/BookCoversNew/You Are Trending In My Dreams Now.jpeg"',
  '  "You Were My Crush Hindi": "/BookCoversNew/You were my crush till you said you love me.jpg"',
  '  "You Were My Crush": "/BookCoversNew/You were my crush till you said you love me.jpg"',
  '  "Your Dreams are Mine Now": "/BookCoversNew/Your Dreams Are Mine Now Novel.jpeg"'
];

// Add comma if needed and insert new mappings
const needsComma = !beforeClosingBrace.trim().endsWith(',');
const separator = needsComma ? ',\n' : '\n';

// Create updated content
const updatedContent = beforeClosingBrace + separator + missingMappings.join(',\n') + '\n' + afterClosingBrace;

// Write the updated file
fs.writeFileSync('src/utils/bookCoverMapping.ts', updatedContent);
console.log(`✓ Added ${missingMappings.length} missing mappings to bookCoverMapping.ts`);