// Auto-generated book cover mapping
// Generated on: 2025-10-29T21:55:48.772Z
// Total covers: 349

/**
 * Gets the cover image path for a book title
 * @param title The book title to find a cover for
 * @returns The path to the cover image or a default image if not found
 */
export function getBookCover(title: string): string {
  if (!title) return '/placeholder.svg';
  
  // Try to find an exact match
  if (bookCoverMap[title]) {
    return bookCoverMap[title];
  }
  
  // Try case-insensitive match
  const lowerTitle = title.toLowerCase();
  const key = Object.keys(bookCoverMap).find(k => 
    k.toLowerCase() === lowerTitle
  );
  
  if (key) {
    return bookCoverMap[key];
  }
  
  // Try partial match (if title contains or is contained in a key)
  const partialMatch = Object.keys(bookCoverMap).find(k => 
    k.toLowerCase().includes(lowerTitle) || 
    lowerTitle.includes(k.toLowerCase())
  );
  
  if (partialMatch) {
    console.log(`Found partial match for "${title}": using cover for "${partialMatch}"`);
    return bookCoverMap[partialMatch];
  }
  
  // Try matching by removing common words and punctuation
  const simplifiedTitle = lowerTitle
    .replace(/[^\w\s]/g, '') // Remove punctuation
    .replace(/\b(the|a|an|and|or|but|in|on|at|by|for|with|about)\b/g, '') // Remove common words
    .trim();
  
  if (simplifiedTitle) {
    const simplifiedMatch = Object.keys(bookCoverMap).find(k => {
      const simplifiedKey = k.toLowerCase()
        .replace(/[^\w\s]/g, '')
        .replace(/\b(the|a|an|and|or|but|in|on|at|by|for|with|about)\b/g, '')
        .trim();
      return simplifiedKey === simplifiedTitle || 
             simplifiedKey.includes(simplifiedTitle) || 
             simplifiedTitle.includes(simplifiedKey);
    });
    
    if (simplifiedMatch) {
      console.log(`Found simplified match for "${title}": using cover for "${simplifiedMatch}"`);
      return bookCoverMap[simplifiedMatch];
    }
  }
  
  // Log missing cover for debugging
  console.warn(`No cover found for book: "${title}"`);
  
  // Return placeholder if no match found
  return '/placeholder.svg';
}

export const bookCoverMap: Record<string, string> = {
  "10 ways to write effective ads": "/BookCoversNew/10 ways to write effective ads.png",
  "100 Selected Short Stories": "/BookCoversNew/100 Selected Short Stories.jpeg",
  "100 years of best American stories": "/BookCoversNew/100 years of best American stories.png",
  "12th Fail": "/BookCoversNew/12th Fail.png",
  "2 States The Story Of My Marriage": "/BookCoversNew/2 States The Story Of My Marriage.png",
  "5 points someone what not to do at iit": "/BookCoversNew/5 points someone what not to do at iit.jpg",
  "50 stories in easy english": "/BookCoversNew/50 stories in easy english.png",
  "A Day In The Life Robert Greenfield": "/BookCoversNew/A Day In The Life Robert Greenfield.jpeg",
  "Accidental love": "/BookCoversNew/Accidental love.png",
  "Akbar Aur Birbal": "/BookCoversNew/Akbar Aur Birbal.jpeg",
  "Albert Einstein": "/BookCoversNew/Albert Einstein.jpg",
  "American short stories": "/BookCoversNew/American short stories.jpg",
  "An Introduction To Buddhism": "/BookCoversNew/An Introduction To Buddhism.jpg",
  "An Unexpected Gift": "/BookCoversNew/An Unexpected Gift.jpg",
  "Angels and demons": "/BookCoversNew/Angels and demons.png",
  "Attitude Is Everything": "/BookCoversNew/Attitude Is Everything.jpg",
  "Ayurveda Divine Science Of Life": "/BookCoversNew/Ayurveda Divine Science Of Life.jpg",
  "Becoming your best self": "/BookCoversNew/Becoming your best self.jpg",
  "Black Hole Physics": "/BookCoversNew/Black Hole Physics.jpg",
  "Buddha S Brain": "/BookCoversNew/Buddha S Brain.jpg",
  "Charlie Chaplin S Biography": "/BookCoversNew/Charlie Chaplin S Biography.png",
  "Chicot the jester": "/BookCoversNew/Chicot the jester.png",
  "Dan Brown Origin": "/BookCoversNew/Dan Brown Origin.jpg",
  "Don T Feed The Monkey Mind": "/BookCoversNew/Don T Feed The Monkey Mind.jpg",
  "Eleven minutes": "/BookCoversNew/Eleven minutes.png",
  "Emotional Intelligence": "/BookCoversNew/Emotional Intelligence.jpg",
  "English Fairy tales": "/BookCoversNew/English Fairy tales.png",
  "English through short stories and jokes": "/BookCoversNew/English through short stories and jokes.png",
  "Essentials Of Pharmacoeconomics": "/BookCoversNew/Essentials Of Pharmacoeconomics.jpg",
  "Finish what you start": "/BookCoversNew/Finish what you start.jpg",
  "First We Make The Beast Beautiful": "/BookCoversNew/First We Make The Beast Beautiful.jpg",
  "Frankstein": "/BookCoversNew/Frankstein.png",
  "General Knowledge From The Quaran": "/BookCoversNew/General Knowledge From The Quaran.jpg",
  "Gone Girl": "/BookCoversNew/Gone Girl.jpg",
  "Grandma S Bag Of Stories": "/BookCoversNew/Grandma S Bag Of Stories.jpg",
  "Gunahon Ka Devta": "/BookCoversNew/Gunahon Ka Devta.jpeg",
  "Gunahon ka devta": "/BookCoversNew/Gunahon ka devta.png",
  "Half Girlfriend": "/BookCoversNew/Half Girlfriend.jpg",
  "Harry Potter And The Chamber Of Secrets": "/BookCoversNew/Harry Potter And The Chamber Of Secrets.jpg",
  "Harry Potter Complete Collection": "/BookCoversNew/Harry Potter Complete Collection.jpg",
  "Harry Potter and the deathly hallows": "/BookCoversNew/Harry Potter and the deathly hallows.jpg",
  "Harry Potter and the goblet of fire": "/BookCoversNew/Harry Potter and the goblet of fire.jpg",
  "Harry Potter and the half blood prince": "/BookCoversNew/Harry Potter and the half blood prince.jpg",
  "Harry Potter and the prisoner of azkaban": "/BookCoversNew/Harry Potter and the prisoner of azkaban.jpg",
  "Harry Potter and the sorcerers stone": "/BookCoversNew/Harry Potter and the sorcerers stone.jpg",
  "Harry Potter special": "/BookCoversNew/Harry Potter special.jpg",
  "Hast rekha": "/BookCoversNew/Hast rekha.png",
  "Healing the child within": "/BookCoversNew/Healing the child within.png",
  "Henry And Mudge And Annie S Good Move": "/BookCoversNew/Henry And Mudge And Annie S Good Move.png",
  "Henry And Mudge And The Snowman Plan": "/BookCoversNew/Henry And Mudge And The Snowman Plan.png",
  "Henry And Mudge Annie S Perfect Pet": "/BookCoversNew/Henry And Mudge Annie S Perfect Pet.png",
  "Henry And Mudge Mr Hopper S House": "/BookCoversNew/Henry And Mudge Mr Hopper S House.png",
  "Henry and Mudge and a big sleepover": "/BookCoversNew/Henry and Mudge and a big sleepover.png",
  "Henry and Mudge and a very merry christmas": "/BookCoversNew/Henry and Mudge and a very merry christmas.png",
  "Henry and Mudge and sneaky crackers": "/BookCoversNew/Henry and Mudge and sneaky crackers.png",
  "Henry and Mudge and the bedtime thums": "/BookCoversNew/Henry and Mudge and the bedtime thums.png",
  "Henry and Mudge and the careful cousin": "/BookCoversNew/Henry and Mudge and the careful cousin.png",
  "Henry and Mudge and the cold shivers": "/BookCoversNew/Henry and Mudge and the cold shivers.png",
  "Henry and Mudge and the forever sea": "/BookCoversNew/Henry and Mudge and the forever sea.png",
  "Henry and Mudge and the great grandpa": "/BookCoversNew/Henry and Mudge and the great grandpa.png",
  "Henry and Mudge and the happy cat": "/BookCoversNew/Henry and Mudge and the happy cat.png",
  "Henry and Mudge and the long weekend": "/BookCoversNew/Henry and Mudge and the long weekend.png",
  "Henry and Mudge and the starry night": "/BookCoversNew/Henry and Mudge and the starry night.png",
  "Henry and Mudge and the tall tree house": "/BookCoversNew/Henry and Mudge and the tall tree house.png",
  "Henry and Mudge and the tumbling trip": "/BookCoversNew/Henry and Mudge and the tumbling trip.png",
  "Henry and Mudge and the wild goose": "/BookCoversNew/Henry and Mudge and the wild goose.png",
  "Henry and Mudge and the wild wind": "/BookCoversNew/Henry and Mudge and the wild wind.png",
  "Henry and Mudge in puddle trouble": "/BookCoversNew/Henry and Mudge in puddle trouble.png",
  "Henry and Mudge in the green time": "/BookCoversNew/Henry and Mudge in the green time.png",
  "Henry and Mudge in the sparkle days": "/BookCoversNew/Henry and Mudge in the sparkle days.png",
  "Henry and Mudge take the big test": "/BookCoversNew/Henry and Mudge take the big test.png",
  "Henry and Mudge the first book": "/BookCoversNew/Henry and Mudge the first book.png",
  "Henry and Mudge under the yellow moon": "/BookCoversNew/Henry and Mudge under the yellow moon.png",
  "How To Analyse People": "/BookCoversNew/How To Analyse People.jpg",
  "How To Become A Straight A Student": "/BookCoversNew/How To Become A Straight A Student.jpg",
  "How To Talk To Anyone 92 Trick": "/BookCoversNew/How To Talk To Anyone 92 Trick.jpg",
  "How To Win Every Argument": "/BookCoversNew/How To Win Every Argument.jpg",
  "I Too Had A Love Story": "/BookCoversNew/I Too Had A Love Story.jpg",
  "I am malala": "/BookCoversNew/I am malala.jpg",
  "If It S Not Forever, It S Not Love": "/BookCoversNew/If It S Not Forever, It S Not Love.jpg",
  "India That Is Bharat": "/BookCoversNew/India That Is Bharat.jpg",
  "It S All In The Planets": "/BookCoversNew/It S All In The Planets.png",
  "It S Not How Good You Are, It S How Good You Want To Be": "/BookCoversNew/It S Not How Good You Are, It S How Good You Want To Be.jpg",
  "It Started With A Friend Request": "/BookCoversNew/It Started With A Friend Request.jpg",
  "It happens for a reason": "/BookCoversNew/It happens for a reason.jpg",
  "Kanark": "/BookCoversNew/Kanark.png",
  "Katie in love": "/BookCoversNew/Katie in love.jpg",
  "Learn German with stories": "/BookCoversNew/Learn German with stories.png",
  "Learn Russian with beginner stories": "/BookCoversNew/Learn Russian with beginner stories.png",
  "Like It Happened Yesterday": "/BookCoversNew/Like It Happened Yesterday.jpg",
  "Long Walk To Freedom The Autobigraphy": "/BookCoversNew/Long Walk To Freedom The Autobigraphy.jpeg",
  "Losing My Virginity And All Other Dares": "/BookCoversNew/Losing My Virginity And All Other Dares.jpeg",
  "Love Kisses And All Things Warm": "/BookCoversNew/Love Kisses And All Things Warm.jpeg",
  "Love@facebook": "/BookCoversNew/Love@facebook.jpeg",
  "Lynn Grabhorn Dear God What S Happening To Us": "/BookCoversNew/Lynn Grabhorn Dear God What S Happening To Us.jpeg",
  "Mahabharat Hindi": "/BookCoversNew/Mahabharat Hindi.jpeg",
  "Mahabharat Ved Vyas": "/BookCoversNew/Mahabharat Ved Vyas.jpeg",
  "Mahayoddha Kalki Sword Of Shiva": "/BookCoversNew/Mahayoddha Kalki Sword Of Shiva.jpeg",
  "Mark Twain The adventures of Tom Swain": "/BookCoversNew/Mark Twain The adventures of Tom Swain.jpeg",
  "Mary poppins 1967": "/BookCoversNew/Mary poppins 1967.jpeg",
  "Mauri Valtonen Hannu Karttunen": "/BookCoversNew/Mauri Valtonen Hannu Karttunen.jpeg",
  "Mel Robbins The 5 Second Rule": "/BookCoversNew/Mel Robbins The 5 Second Rule.jpeg",
  "Michael Jordan A Biography": "/BookCoversNew/Michael Jordan A Biography.jpeg",
  "Midnights Children By Salman Rushdie": "/BookCoversNew/Midnights Children By Salman Rushdie.jpeg",
  "Mistakes Like Love And Sex": "/BookCoversNew/Mistakes Like Love And Sex.jpeg",
  "Modern Arabic Short Stories": "/BookCoversNew/Modern Arabic Short Stories.jpeg",
  "Moonwalking With Einstein": "/BookCoversNew/Moonwalking With Einstein.jpeg",
  "Morgan Housel Psychology of Money": "/BookCoversNew/Morgan Housel Psychology of Money.jpeg",
  "Mother Teresa A Biography": "/BookCoversNew/Mother Teresa A Biography.jpeg",
  "My Clingy Girlfriend Madhuri": "/BookCoversNew/My Clingy Girlfriend Madhuri.jpeg",
  "Mystery Short Stories": "/BookCoversNew/Mystery Short Stories.jpeg",
  "Napolean A Biography": "/BookCoversNew/Napolean A Biography.jpeg",
  "Narendra Modi A Political Biography": "/BookCoversNew/Narendra Modi A Political Biography.jpeg",
  "Nelson Mandela A Biography": "/BookCoversNew/Nelson Mandela A Biography.jpeg",
  "Now That You Re Rich, Let S Fall In Love": "/BookCoversNew/Now That You Re Rich, Let S Fall In Love.jpg",
  "Of Course I Love You": "/BookCoversNew/Of Course I Love You.jpeg",
  "Of Course I Love You Till I Found Someone Better": "/BookCoversNew/Of Course I Love You Till I Found Someone Better.jpeg",
  "Oh Yes I M Single, And So Is My Girlfriend": "/BookCoversNew/Oh Yes I M Single, And So Is My Girlfriend.jpg",
  "Ohh Yes I M Single And So Is D": "/BookCoversNew/Ohh Yes I M Single And So Is D.jpeg",
  "Oliver Twist": "/BookCoversNew/Oliver Twist.jpeg",
  "One Arranged Murder": "/BookCoversNew/One Arranged Murder.jpeg",
  "One Hundred Years Of Soltitude": "/BookCoversNew/One Hundred Years Of Soltitude.jpeg",
  "One Indian Girl Chetan Bhagat": "/BookCoversNew/One Indian Girl Chetan Bhagat.jpeg",
  "One Night At Call Center Chetan Bhagat": "/BookCoversNew/One Night At Call Center Chetan Bhagat.jpeg",
  "One night at the call center": "/BookCoversNew/One night at the call center.png",
  "Osho Osho International Foundation": "/BookCoversNew/Osho Osho International Foundation.jpeg",
  "Our Story Needs No Filter Sudeep": "/BookCoversNew/Our Story Needs No Filter Sudeep.jpeg",
  "Outsiders American Short Stories for students of esl": "/BookCoversNew/Outsiders American Short Stories for students of esl.jpeg",
  "PM Nair The Kalam Effect": "/BookCoversNew/PM Nair The Kalam Effect.jpeg",
  "Paulo Caelho A Warrior S Life": "/BookCoversNew/Paulo Caelho A Warrior S Life.jpeg",
  "Paulo Caelho The Alchemist (1993)": "/BookCoversNew/Paulo Caelho The Alchemist (1993).jpeg",
  "Percy Jackson And The Battle Of The Labyrimin": "/BookCoversNew/Percy Jackson And The Battle Of The Labyrimin.jpeg",
  "Percy Jackson And The Last Olympian": "/BookCoversNew/Percy Jackson And The Last Olympian.jpeg",
  "Percy Jackson And The Lightning Thief": "/BookCoversNew/Percy Jackson And The Lightning Thief.jpeg",
  "Percy Jackson And The Sea Of Monsters": "/BookCoversNew/Percy Jackson And The Sea Of Monsters.jpeg",
  "Percy Jackson And The Titan S Curse": "/BookCoversNew/Percy Jackson And The Titan S Curse.jpeg",
  "Picture Dictionary Longman Children": "/BookCoversNew/Picture Dictionary Longman Children.jpeg",
  "Prem Purana Mythological Love Stories": "/BookCoversNew/Prem Purana Mythological Love Stories.jpeg",
  "Presentation Secets Of Steve Jobs": "/BookCoversNew/Presentation Secets Of Steve Jobs.jpeg",
  "Python API Deevelopment Fundamentals": "/BookCoversNew/Python API Deevelopment Fundamentals.jpeg",
  "Rattan Lal Ichhpuja Rajesh Bhatia": "/BookCoversNew/Rattan Lal Ichhpuja Rajesh Bhatia.jpeg",
  "Reasons To Stay Alive Matt Haig": "/BookCoversNew/Reasons To Stay Alive Matt Haig.jpeg",
  "Rebecca": "/BookCoversNew/Rebecca.jpeg",
  "Reconsidering Redd+ Authority Ananya Sharma": "/BookCoversNew/Reconsidering Redd+ Authority Ananya Sharma.jpeg",
  "Reflections Of A Man Amari Soul": "/BookCoversNew/Reflections Of A Man Amari Soul.jpeg",
  "Religious Therapeutics Body": "/BookCoversNew/Religious Therapeutics Body.jpeg",
  "Revolution 2020 Chetan Bhagat": "/BookCoversNew/Revolution 2020 Chetan Bhagat.jpeg",
  "Rich Dads Increase Your Financial IQ": "/BookCoversNew/Rich Dads Increase Your Financial IQ.jpeg",
  "Right Here Right Now Nikita Singh": "/BookCoversNew/Right Here Right Now Nikita Singh.jpeg",
  "Robinson Crusoe": "/BookCoversNew/Robinson Crusoe.jpeg",
  "Ruk Jaana Nahin Nishant Jain": "/BookCoversNew/Ruk Jaana Nahin Nishant Jain.jpeg",
  "SHORT STORIES": "/BookCoversNew/SHORT STORIES.jpeg",
  "STORYCRAFT The Complete Guide to Storytelling": "/BookCoversNew/STORYCRAFT The Complete Guide to Storytelling.jpeg",
  "Sacred Games A Novel": "/BookCoversNew/Sacred Games A Novel.jpeg",
  "Saket": "/BookCoversNew/Saket.png",
  "Satyayoddha Kalki Eye Of Brahma": "/BookCoversNew/Satyayoddha Kalki Eye Of Brahma.jpeg",
  "Scian Of Ikshvaku Ram Chandra": "/BookCoversNew/Scian Of Ikshvaku Ram Chandra.jpeg",
  "Selected Short Stories": "/BookCoversNew/Selected Short Stories.jpeg",
  "She Broke Up I Didn T I Just Kissed": "/BookCoversNew/She Broke Up I Didn T I Just Kissed.jpeg",
  "She Broke Up I Didn T Just Du": "/BookCoversNew/She Broke Up I Didn T Just Du.jpeg",
  "She Broke Up. I Didn T": "/BookCoversNew/She Broke Up. I Didn T.jpg",
  "Short Stories English": "/BookCoversNew/Short Stories English.jpeg",
  "Short Stories For Children": "/BookCoversNew/Short Stories For Children.jpeg",
  "Short Stories For Children For Spoken English Practice": "/BookCoversNew/Short Stories For Children For Spoken English Practice.jpeg",
  "Short Stories For English Courses": "/BookCoversNew/Short Stories For English Courses.jpeg",
  "Shri Ramcharitramanas (Hindi)": "/BookCoversNew/Shri Ramcharitramanas (Hindi).jpeg",
  "Shutter Island": "/BookCoversNew/Shutter Island.jpeg",
  "Sir Arthur Conan Doyle Complete": "/BookCoversNew/Sir Arthur Conan Doyle Complete.jpeg",
  "Small Size Drawing The Human Body": "/BookCoversNew/Small Size Drawing The Human Body.jpeg",
  "Soma in Yoga and Ayurveda": "/BookCoversNew/Soma in Yoga and Ayurveda.jpeg",
  "Someone Like You": "/BookCoversNew/Someone Like You.jpg",
  "Someone Like You Durjoy Datta": "/BookCoversNew/Someone Like You Durjoy Datta.jpeg",
  "Something I Never Told You": "/BookCoversNew/Something I Never Told You.jpeg",
  "Sorry, You Are Not My Type By Sudeep": "/BookCoversNew/Sorry, You Are Not My Type By Sudeep.jpeg",
  "Spanish Short Stories For Beginners": "/BookCoversNew/Spanish Short Stories For Beginners.jpeg",
  "Sri Ramcharitramanas English All Pages": "/BookCoversNew/Sri Ramcharitramanas English All Pages.jpeg",
  "Steal the show for speeches to stage": "/BookCoversNew/Steal the show for speeches to stage.jpeg",
  "Stephen W Hawking The Theory Of Everything": "/BookCoversNew/Stephen W Hawking The Theory Of Everything.jpeg",
  "Stop Overthinking": "/BookCoversNew/Stop Overthinking.jpg",
  "Stories 198": "/BookCoversNew/Stories 198.jpeg",
  "Stories Of Panchatantra": "/BookCoversNew/Stories Of Panchatantra.jpeg",
  "Super Immunity The Essential Nutrition": "/BookCoversNew/Super Immunity The Essential Nutrition.jpeg",
  "SwadeshiChikitsa Vol 1": "/BookCoversNew/SwadeshiChikitsa Vol 1.jpeg",
  "Swami vivekananda biography": "/BookCoversNew/Swami vivekananda biography.png",
  "Sweet Nothings": "/BookCoversNew/Sweet Nothings.jpeg",
  "Sweet Sixteen": "/BookCoversNew/Sweet Sixteen.jpeg",
  "THE THREE MUSKETERS": "/BookCoversNew/THE THREE MUSKETERS.jpeg",
  "Tea For Two And A Piece Of Cake Sudeep Menon": "/BookCoversNew/Tea For Two And A Piece Of Cake Sudeep Menon.jpeg",
  "Tejguru Sirshee Tejparkhiji Mukti": "/BookCoversNew/Tejguru Sirshee Tejparkhiji Mukti.jpeg",
  "Ten Years Later": "/BookCoversNew/Ten Years Later.jpeg",
  "Ten books in one": "/BookCoversNew/Ten books in one.png",
  "Textbook of Ayurveda": "/BookCoversNew/Textbook of Ayurveda.jpeg",
  "Th 3 (Three) Mistakes Of My Life Chetan Bhagat": "/BookCoversNew/Th 3 (Three) Mistakes Of My Life Chetan Bhagat.jpeg",
  "That S The Way We Meet N": "/BookCoversNew/That S The Way We Meet N.jpeg",
  "That S The Way We Meet Sudeep Menon": "/BookCoversNew/That S The Way We Meet Sudeep Menon.jpeg",
  "That S The Way We Met Sudeep Menon": "/BookCoversNew/That S The Way We Met Sudeep Menon.jpeg",
  "The 5 Am Club Robin Sharma": "/BookCoversNew/The 5 Am Club Robin Sharma.jpeg",
  "The 5 Second Rule Transform Your Life": "/BookCoversNew/The 5 Second Rule Transform Your Life.jpeg",
  "The Adventures Of Pinocchio": "/BookCoversNew/The Adventures Of Pinocchio.png",
  "The Alchemist By Paulo Caelho": "/BookCoversNew/The Alchemist By Paulo Caelho.jpeg",
  "The Anxiety And Phobia Workbook": "/BookCoversNew/The Anxiety And Phobia Workbook.jpeg",
  "The Art Of Public Speaking": "/BookCoversNew/The Art Of Public Speaking.png",
  "The Bhagavad Gita A Biography": "/BookCoversNew/The Bhagavad Gita A Biography.jpeg",
  "The Boy In The Striped Pajamas": "/BookCoversNew/The Boy In The Striped Pajamas.jpeg",
  "The Boy With A Broken Heart": "/BookCoversNew/The Boy With A Broken Heart.jpeg",
  "The Call Of The Wild": "/BookCoversNew/The Call Of The Wild.jpeg",
  "The Complete Short Stories": "/BookCoversNew/The Complete Short Stories.jpeg",
  "The Count Of Monte Cristo": "/BookCoversNew/The Count Of Monte Cristo.jpeg",
  "The Courage To Be Disliked": "/BookCoversNew/The Courage To Be Disliked.jpeg",
  "The Davinci Code Dan Brown": "/BookCoversNew/The Davinci Code Dan Brown.jpeg",
  "The Day Of The Jackal": "/BookCoversNew/The Day Of The Jackal.jpeg",
  "The Extraordinary Miss Sunshine": "/BookCoversNew/The Extraordinary Miss Sunshine.jpeg",
  "The Fisher Queens Dyansty": "/BookCoversNew/The Fisher Queens Dyansty.jpeg",
  "The Forty Five Guardsmen": "/BookCoversNew/The Forty Five Guardsmen.jpeg",
  "The Fox Frederick Forysyth": "/BookCoversNew/The Fox Frederick Forysyth.jpeg",
  "The Gifts Of Imperfection": "/BookCoversNew/The Gifts Of Imperfection.jpeg",
  "The Girl I Last Loved Smita Kau": "/BookCoversNew/The Girl I Last Loved Smita Kau.jpeg",
  "The Girl In Room 105": "/BookCoversNew/The Girl In Room 105.jpeg",
  "The Happiness Trap": "/BookCoversNew/The Happiness Trap.jpeg",
  "The House That BJ Built": "/BookCoversNew/The House That BJ Built.jpeg",
  "The Intelligent Investor": "/BookCoversNew/The Intelligent Investor.jpeg",
  "The Jungle Book Nt": "/BookCoversNew/The Jungle Book Nt.jpeg",
  "The Jungle Book Rudyard Kipling": "/BookCoversNew/The Jungle Book Rudyard Kipling.jpeg",
  "The Little Mermaid": "/BookCoversNew/The Little Mermaid.jpeg",
  "The Lord Of The Rings 1": "/BookCoversNew/The Lord Of The Rings 1.jpeg",
  "The Lord Of The Rings 2": "/BookCoversNew/The Lord Of The Rings 2.jpeg",
  "The Lord Of The Rings 3": "/BookCoversNew/The Lord Of The Rings 3.jpeg",
  "The Lost Symbol": "/BookCoversNew/The Lost Symbol.jpeg",
  "The Man Who Saved India SARDAR PATEL": "/BookCoversNew/The Man Who Saved India SARDAR PATEL.jpeg",
  "The Merry Adventures Of Robin Hood": "/BookCoversNew/The Merry Adventures Of Robin Hood.jpeg",
  "The Mistakes Of My Life": "/BookCoversNew/The Mistakes Of My Life.jpeg",
  "The Monk Who Sold His Ferrari Robin S Sharma": "/BookCoversNew/The Monk Who Sold His Ferrari Robin S Sharma.jpeg",
  "The Mother I Never Knew": "/BookCoversNew/The Mother I Never Knew.jpeg",
  "The One You Cannot Have": "/BookCoversNew/The One You Cannot Have.jpeg",
  "The One You Cannot Have Preti Shenoy": "/BookCoversNew/The One You Cannot Have Preti Shenoy.jpeg",
  "The Palace Of Illusions": "/BookCoversNew/The Palace Of Illusions.jpeg",
  "The Paradoxical Prime Minister": "/BookCoversNew/The Paradoxical Prime Minister.jpeg",
  "The Pilgrimage": "/BookCoversNew/The Pilgrimage.jpeg",
  "The Promise Nikita Singh": "/BookCoversNew/The Promise Nikita Singh.jpeg",
  "The Road Less Travelled": "/BookCoversNew/The Road Less Travelled.jpeg",
  "The Science Of Self Healing": "/BookCoversNew/The Science Of Self Healing.jpeg",
  "The Secret": "/BookCoversNew/The Secret.jpeg",
  "The Secret Wish List": "/BookCoversNew/The Secret Wish List.jpeg",
  "The Secret Wishlist Preeti Shenoy": "/BookCoversNew/The Secret Wishlist Preeti Shenoy.jpeg",
  "The Silent Patient": "/BookCoversNew/The Silent Patient.jpeg",
  "The Three Musketeres": "/BookCoversNew/The Three Musketeres.jpeg",
  "The Wheel Of Time": "/BookCoversNew/The Wheel Of Time.jpeg",
  "The World S Best Boyfriend": "/BookCoversNew/The World S Best Boyfriend.jpeg",
  "The Zoya Factor": "/BookCoversNew/The Zoya Factor.jpeg",
  "The adventures of Tom bombadil": "/BookCoversNew/The adventures of Tom bombadil.png",
  "This Love That Feels Right": "/BookCoversNew/This Love That Feels Right.jpeg",
  "Three Ghost Stories": "/BookCoversNew/Three Ghost Stories.jpeg",
  "Three Mistakes Of My Life Chetan Bhagat": "/BookCoversNew/Three Mistakes Of My Life Chetan Bhagat.jpeg",
  "Till The Last Breath": "/BookCoversNew/Till The Last Breath.jpeg",
  "Till The last breath": "/BookCoversNew/Till The last breath.png",
  "Time Stops At Shamli": "/BookCoversNew/Time Stops At Shamli.jpeg",
  "Trade And Grow Rich": "/BookCoversNew/Trade And Grow Rich.jpeg",
  "Trading Price Action Trading Ranges": "/BookCoversNew/Trading Price Action Trading Ranges.jpeg",
  "Undergraduate Topics In Computer Science": "/BookCoversNew/Undergraduate Topics In Computer Science.jpeg",
  "Universal Magick": "/BookCoversNew/Universal Magick.jpeg",
  "Unn Freedom,Paryavaran And Atma Bharat": "/BookCoversNew/Unn Freedom,Paryavaran And Atma Bharat.jpeg",
  "Veronika Decides To Die": "/BookCoversNew/Veronika Decides To Die.jpeg",
  "Very Hungry Cterpillar": "/BookCoversNew/Very Hungry Cterpillar.jpeg",
  "Vicomte De Bragelonne": "/BookCoversNew/Vicomte De Bragelonne.jpeg",
  "Vladmir Nabokov Lolita Penguin Modern Classics": "/BookCoversNew/Vladmir Nabokov Lolita Penguin Modern Classics.jpeg",
  "Wabi Sabi Japanese Wisdom For A Perfectly Imperfect Life": "/BookCoversNew/Wabi Sabi Japanese Wisdom For A Perfectly Imperfect Life.jpeg",
  "What Is Death": "/BookCoversNew/What Is Death.jpeg",
  "When Bad Things Happens To Good People": "/BookCoversNew/When Bad Things Happens To Good People.jpeg",
  "When Dimple Met Rishi": "/BookCoversNew/When Dimple Met Rishi.jpeg",
  "When ONly Love Remains Durjoy Datta": "/BookCoversNew/When ONly Love Remains Durjoy Datta.jpeg",
  "When Only Love Remains -Durjoy Datta": "/BookCoversNew/When Only Love Remains -Durjoy Datta .jpeg",
  "Wilde Oscar Short Stories": "/BookCoversNew/Wilde Oscar Short Stories.jpeg",
  "Will You Still Love Me Ravindra Singh": "/BookCoversNew/Will You Still Love Me Ravindra Singh.jpeg",
  "Wings of fire": "/BookCoversNew/Wings of fire.jpg",
  "Wonder": "/BookCoversNew/Wonder.jpeg",
  "World S Best Boyfriend": "/BookCoversNew/World S Best Boyfriend.jpg",
  "World S Best Boyfriend Durjoy Datta": "/BookCoversNew/World S Best Boyfriend Durjoy Datta.jpeg",
  "You Are The Best Wife": "/BookCoversNew/You Are The Best Wife.jpeg",
  "You Are Trending In My Dreams Now": "/BookCoversNew/You Are Trending In My Dreams Now.jpeg",
  "You Are Trending In My Dreams Sudeep": "/BookCoversNew/You Are Trending In My Dreams Sudeep.jpeg",
  "You Re The Password Of My Life": "/BookCoversNew/You Re The Password Of My Life.jpeg",
  "You Were My Crush Till You Said Durjoy Datta": "/BookCoversNew/You Were My Crush Till You Said Durjoy Datta.jpeg",
  "You were my crush till you said you love me": "/BookCoversNew/You were my crush till you said you love me.jpg",
  "Your Dreams Are Mine Now Novel": "/BookCoversNew/Your Dreams Are Mine Now Novel.jpeg",
  "Your Dreams Are Mine Now Ravindra": "/BookCoversNew/Your Dreams Are Mine Now Ravindra.jpeg",
  "a half baked love story": "/BookCoversNew/a half baked love story.jpg",
  "a little life": "/BookCoversNew/a little life.jpg",
  "a second chance": "/BookCoversNew/a second chance.jpg",
  "a textbook of dravyaguna": "/BookCoversNew/a textbook of dravyaguna.jpg",
  "accidentally in love": "/BookCoversNew/accidentally in love.jpg",
  "advantage love": "/BookCoversNew/advantage love.jpg",
  "adventures of huckleberry fins": "/BookCoversNew/adventures of huckleberry fins.jpg",
  "american folktales": "/BookCoversNew/american folktales.jpg",
  "atomic habits": "/BookCoversNew/atomic habits.jpg",
  "ayurveda": "/BookCoversNew/ayurveda.jpg",
  "bared to you": "/BookCoversNew/bared to you.jpg",
  "can love happen twice": "/BookCoversNew/can love happen twice.jpg",
  "charitraheen": "/BookCoversNew/charitraheen.jpg",
  "chikitsa sutra": "/BookCoversNew/chikitsa sutra.jpg",
  "coronavirus": "/BookCoversNew/coronavirus.jpg",
  "crime and punishment": "/BookCoversNew/crime and punishment.jpg",
  "drawing cartoons and comics for dummies": "/BookCoversNew/drawing cartoons and comics for dummies.jpg",
  "ego is the enemy": "/BookCoversNew/ego is the enemy.jpg",
  "elmers friend": "/BookCoversNew/elmers friend.jpg",
  "elmers special day": "/BookCoversNew/elmers special day.jpg",
  "fables and stories": "/BookCoversNew/fables and stories.jpg",
  "feeling good": "/BookCoversNew/feeling good.jpg",
  "few things left unsaid": "/BookCoversNew/few things left unsaid.jpg",
  "genius foods": "/BookCoversNew/genius foods.jpg",
  "get epic shit done": "/BookCoversNew/get epic shit done.jpg",
  "give and take": "/BookCoversNew/give and take.jpg",
  "granny and zooey": "/BookCoversNew/granny and zooey.jpg",
  "harry-potter-1-philosophers-stone": "/BookCoversNew/harry-potter-1-philosophers-stone.png",
  "harry-potter-2-chamber-of-secrets": "/BookCoversNew/harry-potter-2-chamber-of-secrets.png",
  "harry-potter-3-prisoner-of-azkaban": "/BookCoversNew/harry-potter-3-prisoner-of-azkaban.png",
  "harry-potter-4-goblet-of-fire": "/BookCoversNew/harry-potter-4-goblet-of-fire.png",
  "harry-potter-5-order-of-phoenix": "/BookCoversNew/harry-potter-5-order-of-phoenix.png",
  "harry-potter-6-half-blood-prince": "/BookCoversNew/harry-potter-6-half-blood-prince.png",
  "harry-potter-7-deathly-hallows": "/BookCoversNew/harry-potter-7-deathly-hallows.png",
  "harry-potter-8-cursed-child": "/BookCoversNew/harry-potter-8-cursed-child.png",
  "healing depression the mind body way": "/BookCoversNew/healing depression the mind body way.jpg",
  "hold my hand": "/BookCoversNew/hold my hand.jpg",
  "hold my hand(1)": "/BookCoversNew/hold my hand(1).jpg",
  "hotel": "/BookCoversNew/hotel.jpg",
  "house of cards": "/BookCoversNew/house of cards.jpg",
  "how I topped the upsc": "/BookCoversNew/how I topped the upsc.jpg",
  "how to read people like a book": "/BookCoversNew/how to read people like a book.jpg",
  "i too had love story": "/BookCoversNew/i too had love story.jpg",
  "images (2)": "/BookCoversNew/images (2).jpeg",
  "inferno": "/BookCoversNew/inferno.jpg",
  "legal eagles": "/BookCoversNew/legal eagles.jpg",
  "life is what you make it": "/BookCoversNew/life is what you make it.jpg",
  "long walk to Freedom": "/BookCoversNew/long walk to Freedom.jpg",
  "microprocessor and microcontroller system": "/BookCoversNew/microprocessor and microcontroller system.jpg",
  "of course I love you": "/BookCoversNew/of course I love you.jpg",
  "our impossible love": "/BookCoversNew/our impossible love.jpg",
  "pingpdf.com The girl of my dreams": "/BookCoversNew/pingpdf.com The girl of my dreams.jpeg",
  "rahat indori": "/BookCoversNew/rahat indori.jpg",
  "second edition computer science handbook": "/BookCoversNew/second edition computer science handbook.jpg",
  "sorry you are not my type": "/BookCoversNew/sorry you are not my type.jpeg",
  "stories": "/BookCoversNew/stories.jpeg",
  "the colossus of rome": "/BookCoversNew/the colossus of rome.jpg",
  "the ritual": "/BookCoversNew/the ritual.jpg",
  "the way of the superior man": "/BookCoversNew/the way of the superior man.jpg",
  "think like a monk": "/BookCoversNew/think like a monk.jpg",
  "tum meru crush ho": "/BookCoversNew/tum meru crush ho.jpg",
  "winning habits": "/BookCoversNew/winning habits.jpg",
  "दो बैलों की कथा": "/BookCoversNew/दो बैलों की कथा.png"
};
