// Book cover mapping based on book_cover_match_report.md
// Maps book titles to their corresponding cover images

export const bookCoverMapping: Record<string, string> = {
  // Exact matches from the report
  "2 States The story of my Marriage": "/BookCoversNew/2 States The Story Of My Marriage.png",
  "A Half Baked Love Story": "/BookCoversNew/a half baked love story.jpg",
  "A Little Life": "/BookCoversNew/a little life.jpg",
  "A Second Chance": "/BookCoversNew/a second chance.jpg",
  "Accidental Love": "/BookCoversNew/Accidental love.png",
  "Accidentally in Love": "/BookCoversNew/accidentally in love.jpg",
  "Advantage Love": "/BookCoversNew/advantage love.jpg",
  "Albert Einstein": "/BookCoversNew/Albert Einstein.jpg",
  "American Short Stories": "/BookCoversNew/American short stories.jpg",
  "An Introduction To Buddhism": "/BookCoversNew/An Introduction To Buddhism.jpg",
  "An Unexpected Gift": "/BookCoversNew/An Unexpected Gift.jpg",
  "Atomic Habits": "/BookCoversNew/atomic habits.jpg",
  "Attitude is Everything": "/BookCoversNew/Attitude Is Everything.jpg",
  "Bared to You": "/BookCoversNew/bared to you.jpg",
  "Becoming Your Best Self": "/BookCoversNew/Becoming your best self.jpg",
  "Can Love Happen Twice": "/BookCoversNew/can love happen twice.jpg",
  "Charitraheen": "/BookCoversNew/charitraheen.jpg",
  "Chicot the Jester": "/BookCoversNew/Chicot the jester.png",
  "Chikitsa Sutra": "/BookCoversNew/chikitsa sutra.jpg",
  "CORONAVIRUS": "/BookCoversNew/coronavirus.jpg",
  "Crime and Punishment": "/BookCoversNew/crime and punishment.jpg",
  "Dan Brown Origin": "/BookCoversNew/Dan Brown Origin.jpg",
  "Don't Feed the Monkey Mind": "/BookCoversNew/Don T Feed The Monkey Mind.jpg",
  "Ego is the Enemy": "/BookCoversNew/ego is the enemy.jpg",
  "Eleven Minutes": "/BookCoversNew/Eleven minutes.png",
  "Emotional Intelligence": "/BookCoversNew/Emotional Intelligence.jpg",
  "Essentials of Pharmacoeconomics": "/BookCoversNew/Essentials Of Pharmacoeconomics.jpg",
  "Fables and Stories": "/BookCoversNew/fables and stories.jpg",
  "Feeling Good": "/BookCoversNew/feeling good.jpg",
  "Few Things Left Unsaid": "/BookCoversNew/few things left unsaid.jpg",
  "Finish What You Start": "/BookCoversNew/Finish what you start.jpg",
  "First We Make the Beast Beautiful": "/BookCoversNew/First We Make The Beast Beautiful.jpg",
  "Genius Foods": "/BookCoversNew/genius foods.jpg",
  "Get Epic Shit Done": "/BookCoversNew/get epic shit done.jpg",
  "Give and Take": "/BookCoversNew/give and take.jpg",
  "Gone Girl": "/BookCoversNew/Gone Girl.jpg",
  "Grandma's Bag of Stories": "/BookCoversNew/Grandma S Bag Of Stories.jpg",
  "Gunahon Ka Devta": "/BookCoversNew/Gunahon Ka Devta.png",
  "Half Girlfriend": "/BookCoversNew/Half Girlfriend.jpg",
  "Harry Potter and the Chamber of Secrets": "/BookCoversNew/Harry Potter And The Chamber Of Secrets.jpg",
  "Harry Potter and the Deathly Hallows": "/BookCoversNew/Harry Potter and the deathly hallows.jpg",
  "Harry Potter and the Goblet of FIre": "/BookCoversNew/Harry Potter and the goblet of fire.jpg",
  "Harry Potter and the Half Blood Prince": "/BookCoversNew/Harry Potter and the half blood prince.jpg",
  "Harry Potter and the Prisoner of Azkaban": "/BookCoversNew/Harry Potter and the prisoner of azkaban.jpg",
  "Harry Potter Complete Collection": "/BookCoversNew/Harry Potter Complete Collection.jpg",
  "Hast Rekha": "/BookCoversNew/Hast rekha.png",
  "Healing Depression The Mind Body Way": "/BookCoversNew/healing depression the mind body way.jpg",
  "Healing the Child Within": "/BookCoversNew/Healing the child within.png",
  "Henry and Mudge and a Very Merry Christmas": "/BookCoversNew/Henry and Mudge and a very merry christmas.png",
  "Henry and Mudge and the Careful Cousin": "/BookCoversNew/Henry and Mudge and the careful cousin.png",
  "Henry and Mudge and the Forever Sea": "/BookCoversNew/Henry and Mudge and the forever sea.png",
  "Henry and Mudge and the Happy Cat": "/BookCoversNew/Henry and Mudge and the happy cat.png",
  "Henry and Mudge and the Long Weekend": "/BookCoversNew/Henry and Mudge and the long weekend.png",
  "Henry and Mudge and the Snowman Plan": "/BookCoversNew/Henry And Mudge And The Snowman Plan.png",
  "Henry and Mudge and the Tall Tree House": "/BookCoversNew/Henry and Mudge and the tall tree house.png",
  "Henry and Mudge and the Tumbling Trip": "/BookCoversNew/Henry and Mudge and the tumbling trip.png",
  "Henry and Mudge and the Wild Wind": "/BookCoversNew/Henry and Mudge and the wild wind.png",
  "Henry and Mudge in Puddle Trouble": "/BookCoversNew/Henry and Mudge in puddle trouble.png",
  "Henry and Mudge in the Green Time": "/BookCoversNew/Henry and Mudge in the green time.png",
  "Henry and Mudge in the Sparkle Days": "/BookCoversNew/Henry and Mudge in the sparkle days.png",
  "Henry and Mudge Take the Big Test": "/BookCoversNew/Henry and Mudge take the big test.png",
  "Henry and Mudge Under the Yellow Moon": "/BookCoversNew/Henry and Mudge under the yellow moon.png",
  "HOLD MY HAND": "/BookCoversNew/hold my hand(1).jpg",
  "House of Cards": "/BookCoversNew/house of cards.jpg",
  "How to Become a Straight A Student": "/BookCoversNew/How To Become A Straight A Student.jpg",
  "How to Read People Like a Book": "/BookCoversNew/how to read people like a book.jpg",
  "How to Win Every Argument": "/BookCoversNew/How To Win Every Argument.jpg",
  "I Too had a Love Story": "/BookCoversNew/I Too Had A Love Story.jpg",
  "India that is Bharat": "/BookCoversNew/India That Is Bharat.jpg",
  "Inferno": "/BookCoversNew/inferno.jpg",
  "It Happens for a Reason": "/BookCoversNew/It happens for a reason.jpg",
  "It Started with a Friend Request": "/BookCoversNew/It Started With A Friend Request.jpg",
  "It's Not How Good You Are, It's How Good You Want to Be": "/BookCoversNew/It S Not How Good You Are, It S How Good You Want To Be.jpg",
  "Katie In Love": "/BookCoversNew/Katie in love.jpg",
  "Life Is What You Make It": "/BookCoversNew/life is what you make it.jpg",
  "Like It Happened Yesterday": "/BookCoversNew/Like It Happened Yesterday.jpg",
  "Long Walk to Freedom": "/BookCoversNew/long walk to Freedom.jpg",
  "Love Kisses And All Things Warm": "/BookCoversNew/Love Kisses And All Things Warm.jpeg",
  "love@facebook": "/BookCoversNew/Love@facebook.jpeg",
  "Mahayoddha Kalki  Sword of Shiva": "/BookCoversNew/Mahayoddha Kalki Sword Of Shiva.jpeg",
  "Michael Jordan A Biography": "/BookCoversNew/Michael Jordan A Biography.jpeg",
  "Midnights Children by Salman Rushdie": "/BookCoversNew/Midnights Children By Salman Rushdie.jpeg",
  "Mistakes Like Love and Sex": "/BookCoversNew/Mistakes Like Love And Sex.jpeg",
  "Modern Arabic Short Stories": "/BookCoversNew/Modern Arabic Short Stories.jpeg",
  "Moonwalking with Einstein": "/BookCoversNew/Moonwalking With Einstein.jpeg",
  "Mother Teresa - A Biography": "/BookCoversNew/Mother Teresa A Biography.jpeg",
  "Mystery Short Stories": "/BookCoversNew/Mystery Short Stories.jpeg",
  "Narendra Modi A Political Biography": "/BookCoversNew/Narendra Modi A Political Biography.jpeg",
  "Nelson Mandela A Biography": "/BookCoversNew/Nelson Mandela A Biography.jpeg",
  "Of Course I Love You": "/BookCoversNew/Of Course I Love You Till I Found Someone Better.jpeg",
  "Oliver Twist": "/BookCoversNew/Oliver Twist.jpeg",
  "One Arranged Murder": "/BookCoversNew/One Arranged Murder.jpeg",
  "One Night at The Call Center": "/BookCoversNew/One night at the call center.png",
  "Our IMPossible Love": "/BookCoversNew/our impossible love.jpg",
  "Percy Jackson and The Last Olympian": "/BookCoversNew/Percy Jackson And The Last Olympian.jpeg",
  "Percy Jackson and The Lightning Thief": "/BookCoversNew/Percy Jackson And The Lightning Thief.jpeg",
  "Percy Jackson and The Sea of Monsters": "/BookCoversNew/Percy Jackson And The Sea Of Monsters.jpeg",
  "Percy Jackson and The Titan s Curse": "/BookCoversNew/Percy Jackson And The Titan S Curse.jpeg",
  "Prem Purana - Mythological Love Stories": "/BookCoversNew/Prem Purana Mythological Love Stories.jpeg",
  "Rebecca": "/BookCoversNew/Rebecca.jpeg",
  "Robinson Crusoe": "/BookCoversNew/Robinson Crusoe.jpeg",
  "Saket": "/BookCoversNew/Saket.png",
  "Satyayoddha Kalki Eye of Brahma": "/BookCoversNew/Satyayoddha Kalki Eye Of Brahma.jpeg",
  "Selected Short Stories": "/BookCoversNew/Selected Short Stories.jpeg",
  "Short stories English": "/BookCoversNew/Short Stories English.jpeg",
  "Short Stories For Children": "/BookCoversNew/Short Stories For Children For Spoken English Practice.jpeg",
  "Short Stories for English Courses": "/BookCoversNew/Short Stories For English Courses.jpeg",
  "SHORT STORIES": "/BookCoversNew/SHORT STORIES.jpeg",
  "Shutter Island": "/BookCoversNew/Shutter Island.jpeg",
  "Soma in Yoga and Ayurveda": "/BookCoversNew/Soma in Yoga and Ayurveda.jpeg",
  "Someone Like You": "/BookCoversNew/Someone Like You Durjoy Datta.jpeg",
  "Something I Never Told You": "/BookCoversNew/Something I Never Told You.jpeg",
  "Sorry You are Not My Type": "/BookCoversNew/sorry you are not my type.jpeg",
  "Spanish Short Stories For Beginners": "/BookCoversNew/Spanish Short Stories For Beginners.jpeg",
  "Stop Overthinking": "/BookCoversNew/Stop Overthinking.jpg",
  "Sweet Nothings": "/BookCoversNew/Sweet Nothings.jpeg",
  "Sweet Sixteen": "/BookCoversNew/Sweet Sixteen.jpeg",
  "Ten Years Later": "/BookCoversNew/Ten Years Later.jpeg",
  "Textbook of Ayurveda": "/BookCoversNew/Textbook of Ayurveda.jpeg",
  "The Anxiety and Phobia Workbook": "/BookCoversNew/The Anxiety And Phobia Workbook.jpeg",
  "The Art of Public Speaking": "/BookCoversNew/The Art Of Public Speaking.png",
  "The Boy in The Striped Pajamas": "/BookCoversNew/The Boy In The Striped Pajamas.jpeg",
  "The Boy with a Broken Heart": "/BookCoversNew/The Boy With A Broken Heart.jpeg",
  "The Call of the Wild": "/BookCoversNew/The Call Of The Wild.jpeg",
  "The Complete Short Stories": "/BookCoversNew/The Complete Short Stories.jpeg",
  "The Courage to be Disliked": "/BookCoversNew/The Courage To Be Disliked.jpeg",
  "The Day of the Jackal": "/BookCoversNew/The Day Of The Jackal.jpeg",
  "The Extraordinary Miss Sunshine": "/BookCoversNew/The Extraordinary Miss Sunshine.jpeg",
  "The Forty-Five Guardsmen": "/BookCoversNew/The Forty Five Guardsmen.jpeg",
  "The Gifts of Imperfection": "/BookCoversNew/The Gifts Of Imperfection.jpeg",
  "The Girl in Room 105": "/BookCoversNew/The Girl In Room 105.jpeg",
  "The Happiness Trap": "/BookCoversNew/The Happiness Trap.jpeg",
  "The House That BJ Built": "/BookCoversNew/The House That BJ Built.jpeg",
  "The Intelligent Investor": "/BookCoversNew/The Intelligent Investor.jpeg",
  "The Little Mermaid": "/BookCoversNew/The Little Mermaid.jpeg",
  "The Lost Symbol": "/BookCoversNew/The Lost Symbol.jpeg",
  "The Merry Adventures of Robin Hood": "/BookCoversNew/The Merry Adventures Of Robin Hood.jpeg",
  "The Mother I Never  Knew": "/BookCoversNew/The Mother I Never Knew.jpeg",
  "THE ONE YOU CANNOT HAVE": "/BookCoversNew/The One You Cannot Have Preti Shenoy.jpeg",
  "The Palace of Illusions": "/BookCoversNew/The Palace Of Illusions.jpeg",
  "The Paradoxical Prime Minister": "/BookCoversNew/The Paradoxical Prime Minister.jpeg",
  "The Pilgrimage": "/BookCoversNew/The Pilgrimage.jpeg",
  "The Ritual": "/BookCoversNew/the ritual.jpg",
  "The Science of Self Healing": "/BookCoversNew/The Science Of Self Healing.jpeg",
  "The Secret Wish List": "/BookCoversNew/The Secret Wish List.jpeg",
  "The Secret": "/BookCoversNew/The Secret Wish List.jpeg",
  "The Way of the Superior Man": "/BookCoversNew/the way of the superior man.jpg",
  "The Wheel of Time": "/BookCoversNew/The Wheel Of Time.jpeg",
  "The Zoya Factor": "/BookCoversNew/The Zoya Factor.jpeg",
  "Think Like A Monk": "/BookCoversNew/think like a monk.jpg",
  "This Love that Feels Right . . .": "/BookCoversNew/This Love That Feels Right.jpeg",
  "Three Ghost Stories": "/BookCoversNew/Three Ghost Stories.jpeg",
  "Till The Last Breath": "/BookCoversNew/Till The Last Breath.jpeg",
  "Trade and Grow Rich": "/BookCoversNew/Trade And Grow Rich.jpeg",
  "Universal Magick": "/BookCoversNew/Universal Magick.jpeg",
  "Veronika Decides to Die": "/BookCoversNew/Veronika Decides To Die.jpeg",
  "Vicomte de Bragelonne": "/BookCoversNew/Vicomte De Bragelonne.jpeg",
  "Wabi Sabi Japanese Wisdom for a Perfectly Imperfect Life": "/BookCoversNew/Wabi Sabi Japanese Wisdom For A Perfectly Imperfect Life.jpeg",
  "What is Death": "/BookCoversNew/What Is Death.jpeg",
  "When Dimple Met Rishi": "/BookCoversNew/When Dimple Met Rishi.jpeg",
  "Wilde Oscar Short Stories": "/BookCoversNew/Wilde Oscar Short Stories.jpeg",
  "Wings Of Fire": "/BookCoversNew/Wings of fire.jpg",
  "Winning Habits": "/BookCoversNew/winning habits.jpg",
  "Wonder": "/BookCoversNew/Wonder.jpeg",
  "World's Best Boyfriend": "/BookCoversNew/World S Best Boyfriend Durjoy Datta.jpeg",
  "You Were My Crush Till You Said You Love Me": "/BookCoversNew/You were my crush till you said you love me.jpg",
  "यन फरडम परयवरण और आतम नरभरत": "/BookCoversNew/यन फरडम परयवरण और आतम नरभरत.png",
  
  // Additional matches from similarity analysis
  "10 Books in 1": "/BookCoversNew/Ten books in one.png",
  "10 Ways to Write More Effective Ads": "/BookCoversNew/10 ways to write effective ads.png",
  "100 years of the best American short stories": "/BookCoversNew/100 years of best American stories.png",
  "12Th Fail (Hindi Novel)": "/BookCoversNew/12th Fail.png",
  "50 Stories in English": "/BookCoversNew/50 stories in easy english.png",
  "A Day in the Life": "/BookCoversNew/A Day In The Life Robert Greenfield.jpeg",
  "A Text Book of Dravyaguna Vijnana": "/BookCoversNew/a textbook of dravyaguna.jpg",
  "A Warrior's Life": "/BookCoversNew/Paulo Caelho A Warrior S Life.jpeg",
  "Adventures of Huckleberry Finn": "/BookCoversNew/adventures of huckleberry fins.jpg",
  "Adventures of Pinocchio": "/BookCoversNew/The Adventures Of Pinocchio.png",
  "Adventures of Tom Bombadil": "/BookCoversNew/The adventures of Tom bombadil.png",
  "Akbar And Birbal": "/BookCoversNew/Akbar Aur Birbal.jpeg",
  "Allen B Tucker Computer Science and Engineering Handbook": "/BookCoversNew/second edition computer science handbook.jpg",
  "American Folk Tales": "/BookCoversNew/american folktales.jpg",
  "Angels & Demons": "/BookCoversNew/Angels and demons.png",
  "Art Of Drawing The Human Body": "/BookCoversNew/Small Size Drawing The Human Body.jpeg",
  "Ayurveda The Divine Science": "/BookCoversNew/ayurveda.jpg",
  "Bhagavad-Gita (Hindi)": "/BookCoversNew/The Bhagavad Gita A Biography.jpeg",
  "Biography of Charlie Chaplin": "/BookCoversNew/Charlie Chaplin S Biography.png",
  "Biography of Swami Vivekananda": "/BookCoversNew/Swami vivekananda biography.png",
  "Buddhas Brain The Practical Neuroscience": "/BookCoversNew/Buddha S Brain.jpg",
  "Dear God! What's Happening to Us": "/BookCoversNew/Lynn Grabhorn Dear God What S Happening To Us.jpeg",
  "Drawing Cartoons and Comics for Dummies ( PDF)": "/BookCoversNew/drawing cartoons and comics for dummies.jpg",
  "Elmer's Special Day": "/BookCoversNew/elmers special day.jpg",
  "English Fairy Tales and More English Fairy Tales": "/BookCoversNew/English Fairy tales.png",
  "English Short Stories": "/BookCoversNew/English through short stories and jokes.png",
  "Franny and Zooey": "/BookCoversNew/granny and zooey.jpg",
  "Harry Potter and the Philosophers Stone": "/BookCoversNew/harry-potter-1-philosophers-stone.png"
};

// Function to get book cover for a given title
export function getBookCover(title: string): string {
  // Try exact match first
  if (bookCoverMapping[title]) {
    return bookCoverMapping[title];
  }
  
  // Try case-insensitive match
  const lowerTitle = title.toLowerCase();
  for (const [key, value] of Object.entries(bookCoverMapping)) {
    if (key.toLowerCase() === lowerTitle) {
      return value;
    }
  }
  
  // Try partial match (first 50 characters)
  const partialTitle = title.substring(0, 50).toLowerCase();
  for (const [key, value] of Object.entries(bookCoverMapping)) {
    if (key.toLowerCase().includes(partialTitle) || partialTitle.includes(key.toLowerCase())) {
      return value;
    }
  }
  
  // Return default cover if no match found
  return "/BookCoversNew/default-book-cover.png";
}