// Book cover mapping based on book_cover_match_report.md
// Maps book titles to their corresponding cover images

export const bookCoverMapping: Record<string, string> = {
  // Exact matches from the report
  "2 States The story of my Marriage": "/BookCoversNew/2 States The Story Of My Marriage.png",
  "A Half Baked Love Story": "/BookCoversNew/a half baked love story.jpg",
  "A Little Life": "/BookCoversNew/a little life.jpg",
  "A Second Chance": "/BookCoversNew/a second chance.jpg",
  "Accidental Love": "/BookCoversNew/Accidental love.png",
  "Accidentally in Love": "/BookCoversNew/accidentally in love.jpg",
  "Advantage Love": "/BookCoversNew/advantage love.jpg",
  "Albert Einstein": "/BookCoversNew/Albert Einstein.jpg",
  "American Short Stories": "/BookCoversNew/American short stories.jpg",
  "An Introduction To Buddhism": "/BookCoversNew/An Introduction To Buddhism.jpg",
  "An Unexpected Gift": "/BookCoversNew/An Unexpected Gift.jpg",
  "Atomic Habits": "/BookCoversNew/atomic habits.jpg",
  "Attitude is Everything": "/BookCoversNew/Attitude Is Everything.jpg",
  "Bared to You": "/BookCoversNew/bared to you.jpg",
  "Becoming Your Best Self": "/BookCoversNew/Becoming your best self.jpg",
  "Can Love Happen Twice": "/BookCoversNew/can love happen twice.jpg",
  "Charitraheen": "/BookCoversNew/charitraheen.jpg",
  "Chicot the Jester": "/BookCoversNew/Chicot the jester.png",
  "Chikitsa Sutra": "/BookCoversNew/chikitsa sutra.jpg",
  "CORONAVIRUS": "/BookCoversNew/coronavirus.jpg",
  "Crime and Punishment": "/BookCoversNew/crime and punishment.jpg",
  "Dan Brown Origin": "/BookCoversNew/Dan Brown Origin.jpg",
  "Don't Feed the Monkey Mind": "/BookCoversNew/Don T Feed The Monkey Mind.jpg",
  "Ego is the Enemy": "/BookCoversNew/ego is the enemy.jpg",
  "Eleven Minutes": "/BookCoversNew/Eleven minutes.png",
  "Emotional Intelligence": "/BookCoversNew/Emotional Intelligence.jpg",
  "Essentials of Pharmacoeconomics": "/BookCoversNew/Essentials Of Pharmacoeconomics.jpg",
  "Fables and Stories": "/BookCoversNew/fables and stories.jpg",
  "Feeling Good": "/BookCoversNew/feeling good.jpg",
  "Few Things Left Unsaid": "/BookCoversNew/few things left unsaid.jpg",
  "Finish What You Start": "/BookCoversNew/Finish what you start.jpg",
  "First We Make the Beast Beautiful": "/BookCoversNew/First We Make The Beast Beautiful.jpg",
  "Genius Foods": "/BookCoversNew/genius foods.jpg",
  "Get Epic Shit Done": "/BookCoversNew/get epic shit done.jpg",
  "Give and Take": "/BookCoversNew/give and take.jpg",
  "Gone Girl": "/BookCoversNew/Gone Girl.jpg",
  "Grandma's Bag of Stories": "/BookCoversNew/Grandma S Bag Of Stories.jpg",
  "Gunahon Ka Devta": "/BookCoversNew/Gunahon Ka Devta.png",
  "Half Girlfriend": "/BookCoversNew/Half Girlfriend.jpg",
  "Harry Potter and the Chamber of Secrets": "/BookCoversNew/Harry Potter And The Chamber Of Secrets.jpg",
  "Harry Potter and the Deathly Hallows": "/BookCoversNew/Harry Potter and the deathly hallows.jpg",
  "Harry Potter and the Goblet of FIre": "/BookCoversNew/Harry Potter and the goblet of fire.jpg",
  "Harry Potter and the Half Blood Prince": "/BookCoversNew/Harry Potter and the half blood prince.jpg",
  "Harry Potter and the Prisoner of Azkaban": "/BookCoversNew/Harry Potter and the prisoner of azkaban.jpg",
  "Harry Potter Complete Collection": "/BookCoversNew/Harry Potter Complete Collection.jpg",
  "Harry Potter and the Philosopher's Stone": "/BookCoversNew/Harry Potter And The Philosopher S Stone.jpg",
  "He's Just Not That Into You": "/BookCoversNew/He S Just Not That Into You.jpg",
  "How I Braved Anu Aunty and Co-Founded a Million Dollar Company": "/BookCoversNew/How I Braved Anu Aunty And Co Founded A Million Dollar Company.jpg",
  "I Too Had a Love Story": "/BookCoversNew/I too had a love story.jpg",
  "If It's Not Forever": "/BookCoversNew/If It S Not Forever.jpg",
  "Ikigai": "/BookCoversNew/ikigai.jpg",
  "In Custody": "/BookCoversNew/in custody.jpg",
  "Interpreter of Maladies": "/BookCoversNew/Interpreter of maladies.jpg",
  "It Ends With Us": "/BookCoversNew/It ends with us.jpg",
  "It Had to Be You": "/BookCoversNew/It had to be you.jpg",
  "It's All In The Planets": "/BookCoversNew/It S All In The Planets.jpg",
  "Journey to the Centre of the Earth": "/BookCoversNew/Journey to the centre of the earth.jpg",
  "Just Married, Please Excuse": "/BookCoversNew/Just married please excuse.jpg",
  "Kafka on the Shore": "/BookCoversNew/Kafka on the shore.jpg",
  "Keep the Change": "/BookCoversNew/Keep the change.jpg",
  "Life is What You Make It": "/BookCoversNew/Life is what you make it.jpg",
  "Like It Happened Yesterday": "/BookCoversNew/Like it happened yesterday.jpg",
  "Love Story": "/BookCoversNew/Love story.jpg",
  "Lust for Life": "/BookCoversNew/Lust for life.jpg",
  "Malgudi Days": "/BookCoversNew/malgudi days.jpg",
  "Man's Search for Meaning": "/BookCoversNew/Man S Search For Meaning.jpg",
  "Maybe Someday": "/BookCoversNew/Maybe someday.jpg",
  "Me Before You": "/BookCoversNew/Me before you.jpg",
  "Memoirs of a Geisha": "/BookCoversNew/Memoirs of a geisha.jpg",
  "Men Are from Mars, Women Are from Venus": "/BookCoversNew/Men are from mars women are from venus.jpg",
  "Message In A Bottle": "/BookCoversNew/Message in a bottle.jpg",
  "Millionaire Next Door": "/BookCoversNew/Millionaire next door.jpg",
  "Mistress of Spices": "/BookCoversNew/Mistress of spices.jpg",
  "My Sister's Keeper": "/BookCoversNew/My sister S keeper.jpg",
  "Naked Face": "/BookCoversNew/Naked face.jpg",
  "NameSake": "/BookCoversNew/Namesake.jpg",
  "Never Never": "/BookCoversNew/Never never.jpg",
  "Norwegian Wood": "/BookCoversNew/Norwegian wood.jpg",
  "Not Without My Daughter": "/BookCoversNew/Not without my daughter.jpg",
  "Nothing Lasts Forever": "/BookCoversNew/Nothing lasts forever.jpg",
  "Of Course I Love You": "/BookCoversNew/Of course I love you.jpg",
  "One Night at the Call Center": "/BookCoversNew/One night at the call center.jpg",
  "One Night Stand": "/BookCoversNew/One night stand.jpg",
  "Our Impossible Love": "/BookCoversNew/Our impossible love.jpg",
  "Perfect Chemistry": "/BookCoversNew/Perfect chemistry.jpg",
  "Pride and Prejudice": "/BookCoversNew/Pride and prejudice.jpg",
  "PS I Love You": "/BookCoversNew/PS I love you.jpg",
  "Rage of Angels": "/BookCoversNew/Rage of angels.jpg",
  "Random Winds": "/BookCoversNew/Random winds.jpg",
  "Red Earth and Pouring Rain": "/BookCoversNew/Red earth and pouring rain.jpg",
  "Rich Dad Poor Dad": "/BookCoversNew/Rich dad poor dad.jpg",
  "Romeo and Juliet": "/BookCoversNew/Romeo and juliet.jpg",
  "Safe Harbour": "/BookCoversNew/Safe harbour.jpg",
  "Screw It Let's Do It": "/BookCoversNew/Screw it let S do it.jpg",
  "Sense and Sensibility": "/BookCoversNew/Sense and sensibility.jpg",
  "She's Come Undone": "/BookCoversNew/She S Come Undone.jpg",
  "Shopaholic Takes Manhattan": "/BookCoversNew/Shopaholic takes manhattan.jpg",
  "Someone Like You": "/BookCoversNew/Someone like you.jpg",
  "Songs of Blood and Sword": "/BookCoversNew/Songs of blood and sword.jpg",
  "Soppy": "/BookCoversNew/Soppy.jpg",
  "Stay Hungry Stay Foolish": "/BookCoversNew/Stay hungry stay foolish.jpg",
  "Steve Jobs": "/BookCoversNew/Steve jobs.jpg",
  "Stranger in My Arms": "/BookCoversNew/Stranger in my arms.jpg",
  "Summer of '42": "/BookCoversNew/Summer of 42.jpg",
  "Tales of Beedle the Bard": "/BookCoversNew/Tales of beedle the bard.jpg",
  "Taming the Infinite": "/BookCoversNew/Taming the infinite.jpg",
  "Tell Me Your Dreams": "/BookCoversNew/Tell me your dreams.jpg",
  "Tess of the D'Urbervilles": "/BookCoversNew/Tess of the d urbervilles.jpg",
  "The 3 Mistakes of My Life": "/BookCoversNew/The 3 mistakes of my life.jpg",
  "The Adventures of Huckleberry Finn": "/BookCoversNew/The adventures of huckleberry finn.jpg",
  "The Adventures of Sherlock Holmes": "/BookCoversNew/The adventures of sherlock holmes.jpg",
  "The Adventures of Tom Sawyer": "/BookCoversNew/The adventures of tom sawyer.jpg",
  "The Alchemist": "/BookCoversNew/The alchemist.jpg",
  "The Art of War": "/BookCoversNew/The art of war.jpg",
  "The Autobiography of Benjamin Franklin": "/BookCoversNew/The autobiography of benjamin franklin.jpg",
  "The Bachelor of Arts": "/BookCoversNew/The bachelor of arts.jpg",
  "The Bankster": "/BookCoversNew/The bankster.jpg",
  "The Beach": "/BookCoversNew/The beach.jpg",
  "The Best of Me": "/BookCoversNew/The best of me.jpg",
  "The Big Picture": "/BookCoversNew/The big picture.jpg",
  "The Black Swan": "/BookCoversNew/The black swan.jpg",
  "The Blind Assassin": "/BookCoversNew/The blind assassin.jpg",
  "The Blue Umbrella": "/BookCoversNew/The blue umbrella.jpg",
  "The Book Thief": "/BookCoversNew/The book thief.jpg",
  "The Bridges of Madison County": "/BookCoversNew/The bridges of madison county.jpg",
  "The Call of the Wild": "/BookCoversNew/The call of the wild.jpg",
  "The Canterville Ghost": "/BookCoversNew/The canterville ghost.jpg",
  "The Catcher in the Rye": "/BookCoversNew/The catcher in the rye.jpg",
  "The Chamber": "/BookCoversNew/The chamber.jpg",
  "The Client": "/BookCoversNew/The client.jpg",
  "The Color Purple": "/BookCoversNew/The color purple.jpg",
  "The Complete Novels of Sherlock Holmes": "/BookCoversNew/The complete novels of sherlock holmes.jpg",
  "The Confession": "/BookCoversNew/The confession.jpg",
  "The Constant Princess": "/BookCoversNew/The constant princess.jpg",
  "The Count of Monte Cristo": "/BookCoversNew/The count of monte cristo.jpg",
  "The Da Vinci Code": "/BookCoversNew/The da vinci code.jpg",
  "The Dark Half": "/BookCoversNew/The dark half.jpg",
  "The Day of the Jackal": "/BookCoversNew/The day of the jackal.jpg",
  "The Devil Wears Prada": "/BookCoversNew/The devil wears prada.jpg",
  "The Diary of a Young Girl": "/BookCoversNew/The diary of a young girl.jpg",
  "The English Teacher": "/BookCoversNew/The english teacher.jpg",
  "The Fault in Our Stars": "/BookCoversNew/The fault in our stars.jpg",
  "The Firm": "/BookCoversNew/The firm.jpg",
  "The Five People You Meet in Heaven": "/BookCoversNew/The five people you meet in heaven.jpg",
  "The Fountainhead": "/BookCoversNew/The fountainhead.jpg",
  "The Girl with the Dragon Tattoo": "/BookCoversNew/The girl with the dragon tattoo.jpg",
  "The God of Small Things": "/BookCoversNew/The god of small things.jpg",
  "The Godfather": "/BookCoversNew/The godfather.jpg",
  "The Golden Gate": "/BookCoversNew/The golden gate.jpg",
  "The Grapes of Wrath": "/BookCoversNew/The grapes of wrath.jpg",
  "The Great Gatsby": "/BookCoversNew/The great gatsby.jpg",
  "The Green Mile": "/BookCoversNew/The green mile.jpg",
  "The Guide": "/BookCoversNew/The guide.jpg",
  "The Help": "/BookCoversNew/The help.jpg",
  "The Hitchhiker's Guide to the Galaxy": "/BookCoversNew/The hitchhiker S guide to the galaxy.jpg",
  "The Hobbit": "/BookCoversNew/The hobbit.jpg",
  "The Hound of the Baskervilles": "/BookCoversNew/The hound of the baskervilles.jpg",
  "The House of the Seven Gables": "/BookCoversNew/The house of the seven gables.jpg",
  "The Hunchback of Notre Dame": "/BookCoversNew/The hunchback of notre dame.jpg",
  "The Iliad": "/BookCoversNew/The iliad.jpg",
  "The Immortals of Meluha": "/BookCoversNew/The immortals of meluha.jpg",
  "The Importance of Being Earnest": "/BookCoversNew/The importance of being earnest.jpg",
  "The Inheritance of Loss": "/BookCoversNew/The inheritance of loss.jpg",
  "The Kite Runner": "/BookCoversNew/The kite runner.jpg",
  "The Last Song": "/BookCoversNew/The last song.jpg",
  "The Little Prince": "/BookCoversNew/The little prince.jpg",
  "The Longest Ride": "/BookCoversNew/The longest ride.jpg",
  "The Lost Symbol": "/BookCoversNew/The lost symbol.jpg",
  "The Lovely Bones": "/BookCoversNew/The lovely bones.jpg",
  "The Magic": "/BookCoversNew/The magic.jpg",
  "The Magic Mountain": "/BookCoversNew/The magic mountain.jpg",
  "The Man in the Iron Mask": "/BookCoversNew/The man in the iron mask.jpg",
  "The Merchant of Venice": "/BookCoversNew/The merchant of venice.jpg",
  "The Millionaire Next Door": "/BookCoversNew/The millionaire next door.jpg",
  "The Mirror Crack'd from Side to Side": "/BookCoversNew/The mirror crack D from side to side.jpg",
  "The Monk Who Sold His Ferrari": "/BookCoversNew/The monk who sold his ferrari.jpg",
  "The Notebook": "/BookCoversNew/The notebook.jpg",
  "The Oath": "/BookCoversNew/The oath.jpg",
  "The Odyssey": "/BookCoversNew/The odyssey.jpg",
  "The Other Side of Midnight": "/BookCoversNew/The other side of midnight.jpg",
  "The Painted Veil": "/BookCoversNew/The painted veil.jpg",
  "The Partner": "/BookCoversNew/The partner.jpg",
  "The Pelican Brief": "/BookCoversNew/The pelican brief.jpg",
  "The Picture of Dorian Gray": "/BookCoversNew/The picture of dorian gray.jpg",
  "The Pilgrimage": "/BookCoversNew/The pilgrimage.jpg",
  "The Pillars of the Earth": "/BookCoversNew/The pillars of the earth.jpg",
  "The Portrait of a Lady": "/BookCoversNew/The portrait of a lady.jpg",
  "The Power of Now": "/BookCoversNew/The power of now.jpg",
  "The Prince": "/BookCoversNew/The prince.jpg",
  "The Princess Bride": "/BookCoversNew/The princess bride.jpg",
  "The Prophet": "/BookCoversNew/The prophet.jpg",
  "The Rainmaker": "/BookCoversNew/The rainmaker.jpg",
  "The Reader": "/BookCoversNew/The reader.jpg",
  "The Return of the Native": "/BookCoversNew/The return of the native.jpg",
  "The Road": "/BookCoversNew/The road.jpg",
  "The Robe": "/BookCoversNew/The robe.jpg",
  "The Runaway Jury": "/BookCoversNew/The runaway jury.jpg",
  "The Scarlet Letter": "/BookCoversNew/The scarlet letter.jpg",
  "The Secret Garden": "/BookCoversNew/The secret garden.jpg",
  "The Seven Spiritual Laws of Success": "/BookCoversNew/The seven spiritual laws of success.jpg",
  "The Shadow Lines": "/BookCoversNew/The shadow lines.jpg",
  "The Shining": "/BookCoversNew/The shining.jpg",
  "The Sicilian": "/BookCoversNew/The sicilian.jpg",
  "The Sixth Man": "/BookCoversNew/The sixth man.jpg",
  "The Sound and the Fury": "/BookCoversNew/The sound and the fury.jpg",
  "The Stand": "/BookCoversNew/The stand.jpg",
  "The Story of My Experiments with Truth": "/BookCoversNew/The story of my experiments with truth.jpg",
  "The Street Lawyer": "/BookCoversNew/The street lawyer.jpg",
  "The Sun Also Rises": "/BookCoversNew/The sun also rises.jpg",
  "The Summons": "/BookCoversNew/The summons.jpg",
  "The Testament": "/BookCoversNew/The testament.jpg",
  "The Time Machine": "/BookCoversNew/The time machine.jpg",
  "The Trial": "/BookCoversNew/The trial.jpg",
  "The Unbearable Lightness of Being": "/BookCoversNew/The unbearable lightness of being.jpg",
  "The Undomestic Goddess": "/BookCoversNew/The undomestic goddess.jpg",
  "The Valley of Fear": "/BookCoversNew/The valley of fear.jpg",
  "The Verdict": "/BookCoversNew/The verdict.jpg",
  "The Vicar of Wakefield": "/BookCoversNew/The vicar of wakefield.jpg",
  "The Wedding": "/BookCoversNew/The wedding.jpg",
  "The White Tiger": "/BookCoversNew/The white tiger.jpg",
  "The Wind in the Willows": "/BookCoversNew/The wind in the willows.jpg",
  "The Witness": "/BookCoversNew/The witness.jpg",
  "The Woman in White": "/BookCoversNew/The woman in white.jpg",
  "The World Is Flat": "/BookCoversNew/The world is flat.jpg",
  "Think and Grow Rich": "/BookCoversNew/Think and grow rich.jpg",
  "This Heart of Mine": "/BookCoversNew/This heart of mine.jpg",
  "Three Men in a Boat": "/BookCoversNew/Three men in a boat.jpg",
  "Through the Looking Glass": "/BookCoversNew/Through the looking glass.jpg",
  "To Kill a Mockingbird": "/BookCoversNew/To kill a mockingbird.jpg",
  "To Sir, With Love": "/BookCoversNew/To sir with love.jpg",
  "Tom Jones": "/BookCoversNew/Tom jones.jpg",
  "Tuesdays with Morrie": "/BookCoversNew/Tuesdays with morrie.jpg",
  "Two States": "/BookCoversNew/Two states.jpg",
  "Ulysses": "/BookCoversNew/Ulysses.jpg",
  "Unaccustomed Earth": "/BookCoversNew/Unaccustomed earth.jpg",
  "Under the Net": "/BookCoversNew/Under the net.jpg",
  "Vanity Fair": "/BookCoversNew/Vanity fair.jpg",
  "Veronika Decides to Die": "/BookCoversNew/Veronika decides to die.jpg",
  "Waiting for Godot": "/BookCoversNew/Waiting for godot.jpg",
  "War and Peace": "/BookCoversNew/War and peace.jpg",
  "Watership Down": "/BookCoversNew/Watership down.jpg",
  "We the Living": "/BookCoversNew/We the living.jpg",
  "What Katy Did": "/BookCoversNew/What katy did.jpg",
  "When Only Love Remains": "/BookCoversNew/When only love remains.jpg",
  "Where the Heart Is": "/BookCoversNew/Where the heart is.jpg",
  "White Teeth": "/BookCoversNew/White teeth.jpg",
  "Wings of Fire": "/BookCoversNew/Wings of fire.jpg",
  "Wuthering Heights": "/BookCoversNew/Wuthering heights.jpg",
  "You Are the Best Wife": "/BookCoversNew/You are the best wife.jpg",
  "You Can Win": "/BookCoversNew/You can win.jpg",
  "Your Erroneous Zones": "/BookCoversNew/Your erroneous zones.jpg",
  "Zero to One": "/BookCoversNew/Zero to one.jpg",
  
  // Additional mappings from the 185 specific missing mappings
  "10 Books in 1": "/BookCoversNew/Ten books in one.png",
  "10 Ways to Write More Effective Ads": "/BookCoversNew/10 ways to write effective ads.png",
  "12Th Fail Hindi Novel": "/BookCoversNew/12th Fail.png",
  "A Day in the Life": "/BookCoversNew/A Day In The Life Robert Greenfield.jpeg",
  "A Text Book of Dravyaguna Vijnana": "/BookCoversNew/a textbook of dravyaguna.jpg",
  "Adventures of Huckleberry Finn": "/BookCoversNew/adventures of huckleberry fins.jpg",
  "Akbar And Birbal": "/BookCoversNew/Akbar Aur Birbal.jpeg",
  "Allen B Tucker Computer Science and Engineering Handbook": "/BookCoversNew/second edition computer science handbook.jpg",
  "American Folk Tales": "/BookCoversNew/american folktales.jpg",
  "Angels Demons": "/BookCoversNew/Angels and demons.png",
  "Ayurveda Treatment for Beginner": "/BookCoversNew/Ayurveda Divine Science Of Life.jpg",
  "Biography of Charlie Chaplin": "/BookCoversNew/Charlie Chaplin S Biography.png",
  "Biography of Swami Vivekananda": "/BookCoversNew/Swami vivekananda biography.png",
  "Buddhas Brain The Practical Neuroscience": "/BookCoversNew/Buddha S Brain.jpg",
  "Complete Sherlock Holmes 1960": "/BookCoversNew/Sir Arthur Conan Doyle Complete.jpeg",
  "Dear God What s Happening to Us": "/BookCoversNew/Lynn Grabhorn Dear God What S Happening To Us.jpeg",
  "Do Bailo Ki Katha": "/BookCoversNew/दो बैलों की कथा.png",
  "Drawing Cartoons and Comics for Dummies PDF": "/BookCoversNew/drawing cartoons and comics for dummies.jpg",
  "Elmer s Friends": "/BookCoversNew/elmers friend.jpg",
  "Elmers s Special Day": "/BookCoversNew/elmers special day.jpg",
  "Essentials of Medical Microbiology": "/BookCoversNew/Essentials of Microbiology.png",
  "Five Point Someone": "/BookCoversNew/5 points someone what not to do at iit.jpg",
  "Frankenstein or The Mordern Prometheus": "/BookCoversNew/Frankstein.png",
  "Fundamental Theories of Physics": "/BookCoversNew/Black Hole Physics.jpg",
  "Guide to Competetive Programming": "/BookCoversNew/Allen B Tucker Computer Science and Engineering Handbook.pdf",
  "Harry Potter and the Philosophers Stone": "/BookCoversNew/harry-potter-1-philosophers-stone.png",
  "50 Stories in English": "/BookCoversNew/50 stories in easy english.png",
  "100 years of the best American short stories": "/BookCoversNew/100 years of best American stories.png",
  "Harry Potter and the Order of the Phoenix": "/BookCoversNew/harry-potter-5-order-of-phoenix.png",
  "Harry Potter and the Cursed Child": "/BookCoversNew/harry-potter-8-cursed-child.png",
  "Healing Depression The Mind Body Way": "/BookCoversNew/healing depression the mind body way.jpg",
  "Henry and Mudge and Annie Good Move": "/BookCoversNew/Henry And Mudge And Annie S Good Move.png",
  "Henry and Mudge and Annie Perfect Pet": "/BookCoversNew/Henry And Mudge Annie S Perfect Pet.png",
  "Henry and Mudge and Mrs Hopper House": "/BookCoversNew/Henry And Mudge Mr Hopper S House.png",
  "Henry and Mudge and the Bedtime Thumps": "/BookCoversNew/Henry and Mudge and the bedtime thums.png",
  "Henry and Mudge and the Big Sleepover": "/BookCoversNew/Henry and Mudge and a big sleepover.png",
  "Henry and Mudge and the Great Grandpas": "/BookCoversNew/Henry and Mudge and the great grandpa.png",
  "Henry and Mudge and the Sneaky Crackers": "/BookCoversNew/Henry and Mudge and sneaky crackers.png",
  "Henry and Mudge and the Starry Night May": "/BookCoversNew/Henry and Mudge and the starry night.png",
  "Henry and Mudge and the Wild Goose Chase": "/BookCoversNew/Henry and Mudge and the wild goose.png",
  "Henry and Mudge Get the Cold Shivers": "/BookCoversNew/Henry and Mudge and the cold shivers.png",
  "Henry and Mudge in the Family Trees": "/BookCoversNew/Henry and Mudge in the green time.png",
  "Henry and Mudge The First Book of Their Adventures": "/BookCoversNew/Henry and Mudge the first book.png",
  "Hotel by Arthur Hailey": "/BookCoversNew/hotel.jpg",
  "How I Topped The UPSC and How You Can Too": "/BookCoversNew/how I topped the upsc.jpg",
  "How to Talk to Anyone 92 Little Tricks for Big Success": "/BookCoversNew/How To Talk To Anyone 92 Trick.jpg",
  "If It s Not Forever": "/BookCoversNew/If It S Not Forever, It S Not Love.jpg",
  "It s Not How Good You Are It s How Good You Want to Be": "/BookCoversNew/It S Not How Good You Are, It S How Good You Want To Be.jpg",
  "Its All In The Planets": "/BookCoversNew/It S All In The Planets.png",
  "Julius Caesar The Colossus of Rome": "/BookCoversNew/the colossus of rome.jpg",
  "Konark Hindi Novel": "/BookCoversNew/Konark.png",
  "Legal Eagles Stories of the Top Seven Indian Lawyers": "/BookCoversNew/legal eagles.jpg",
  "Life is a Soap Bubble": "/BookCoversNew/Life of A Soap Bubble.png",
  "Lord Of The Rings The Return Of The King": "/BookCoversNew/The Lord Of The Rings 1.jpeg",
  "Losing My Virginity and Other Dumb Ideas": "/BookCoversNew/Losing My Virginity And All Other Dares.jpeg",
  "love facebook": "/BookCoversNew/Love@facebook.jpeg",
  "Mahabharat": "/BookCoversNew/Mahabharat Hindi.jpeg",
  "Mahabharata Veda Vyasa eng": "/BookCoversNew/Mahabharat Ved Vyas.jpeg",
  "Mahayoddha Kalki Sword of Shiva": "/BookCoversNew/Mahayoddha Kalki Sword Of Shiva.jpeg",
  "Marry Poppins": "/BookCoversNew/Mary poppins 1967.jpeg",
  "Microprocessors Microcontroller Systems": "/BookCoversNew/microprocessor and microcontroller system.jpg",
  "Mother Teresa A Biography": "/BookCoversNew/Mother Teresa A Biography.jpeg",
  "My Clingy Girlfriend": "/BookCoversNew/My Clingy Girlfriend Madhuri.jpeg",
  "Napoleon A Biography": "/BookCoversNew/Napolean A Biography.jpeg",
  "Now That You are Rich": "/BookCoversNew/You Are Trending In My Dreams Now.jpeg",
  "Oh Yes I m Single": "/BookCoversNew/Oh Yes I M Single, And So Is My Girlfriend.jpg",
  "One Hundred Years Of Solitude": "/BookCoversNew/One Hundred Years Of Soltitude.jpeg",
  "One Indian Girl": "/BookCoversNew/Gone Girl.jpg",
  "Our Story Needs No Filter": "/BookCoversNew/Our Story Needs No Filter Sudeep.jpeg",
  "Outsiders American Short Stories for students of ESL": "/BookCoversNew/Outsiders American Short Stories for students of esl.jpeg",
  "Percy Jackson and The Battle of the Labyrinth": "/BookCoversNew/Percy Jackson And The Battle Of The Labyrimin.jpeg",
  "Picture Dictionary": "/BookCoversNew/Picture Dictionary Longman Children.jpeg",
  "Prem Purana Mythological Love Stories": "/BookCoversNew/Prem Purana Mythological Love Stories.jpeg",
  "Presentation Secrets Of Steve Jobs": "/BookCoversNew/Presentation Secets Of Steve Jobs.jpeg",
  "Python API Development Fundamentals": "/BookCoversNew/Python API Deevelopment Fundamentals.jpeg",
  "Reasons to Stay Alive": "/BookCoversNew/Reasons To Stay Alive Matt Haig.jpeg",
  "Reconsidering REDD Authority Power and Law": "/BookCoversNew/Reconsidering Redd+ Authority Ananya Sharma.jpeg",
  "Reflections Of A Man": "/BookCoversNew/Reflections Of A Man Amari Soul.jpeg",
  "Religious Therapeutics": "/BookCoversNew/Religious Therapeutics Body.jpeg",
  "Revolution 2020": "/BookCoversNew/Revolution 2020 Chetan Bhagat.jpeg",
  "Rich Dads Increase Your Financial IQ Get Smarter with Your Money": "/BookCoversNew/Rich Dads Increase Your Financial IQ.jpeg",
  "Right Here Right Now": "/BookCoversNew/Right Here Right Now Nikita Singh.jpeg",
  "Ruk Jaana Nahin": "/BookCoversNew/Ruk Jaana Nahin Nishant Jain.jpeg",
  "Sacred Games": "/BookCoversNew/Sacred Games A Novel.jpeg",
  "Scion of Ikshvaku": "/BookCoversNew/Scian Of Ikshvaku Ram Chandra.jpeg",
  "Self Liberation From Fear Worry and Angry": "/BookCoversNew/Self Liberation from Fear,Worry and Angry.png",
  "She Broke Up I Didn t": "/BookCoversNew/She Broke Up. I Didn T.jpg",
  "She Broke Up I Didn t I Just Kissed": "/BookCoversNew/She Broke Up I Didn T I Just Kissed.jpeg",
  "She Broke Up I Didn t Just Du": "/BookCoversNew/She Broke Up I Didn T Just Du.jpeg",
  "Short Stories for Children for Spoken English": "/BookCoversNew/Short Stories For Children For Spoken English Practice.jpeg",
  "Short Stories of The Day": "/BookCoversNew/The Complete Short Stories.jpeg",
  "Short-Stories": "/BookCoversNew/stories.jpeg",
  "Shri Ramcharitmanas Hindi": "/BookCoversNew/Shri Ramcharitramanas (Hindi).jpeg",
  "Sri Ramcharitmanas English": "/BookCoversNew/Sri Ramcharitramanas English All Pages.jpeg",
  "Steal the Show": "/BookCoversNew/how I topped the upsc.jpg",
  "Stories From My Teacher": "/BookCoversNew/STORYCRAFT The Complete Guide to Storytelling.jpeg",
  "Stories from PANCHATANTRA": "/BookCoversNew/Stories Of Panchatantra.jpeg",
  "Story Craft": "/BookCoversNew/STORYCRAFT The Complete Guide to Storytelling.jpeg",
  "Super Immunity": "/BookCoversNew/Super Immunity The Essential Nutrition.jpeg",
  "Swadeshi Chikitsa": "/BookCoversNew/SwadeshiChikitsa Vol 1.jpeg",
  "Tea for Two and a Piece of Cake": "/BookCoversNew/Tea For Two And A Piece Of Cake Sudeep Menon.jpeg",
  "Tell The Last Breath": "/BookCoversNew/Till The Last Breath.jpeg",
  "Thats The Way We Met": "/BookCoversNew/That S The Way We Meet N.jpeg",
  "The 3 Three Mistakes of My Life": "/BookCoversNew/The Mistakes Of My Life.jpeg",
  "The 5 Second Rule": "/BookCoversNew/Mel Robbins The 5 Second Rule.jpeg",
  "The 5AM Club": "/BookCoversNew/The 5 Am Club Robin Sharma.jpeg",
  "The adventures of Tom Sawyer (New)": "/BookCoversNew/The adventures of Tom bombadil.png",
  "The Alchemist (Paulo Coelho)": "/BookCoversNew/The Alchemist By Paulo Caelho.jpeg",
  "The Anxiety and Phobia Workbook": "/BookCoversNew/The Anxiety And Phobia Workbook.jpeg",
  "The Art of Public Speaking": "/BookCoversNew/The Art Of Public Speaking.png",
  "The Bhagavad Gita": "/BookCoversNew/The Bhagavad Gita A Biography.jpeg",
  "The Boy in The Striped Pajamas": "/BookCoversNew/The Boy In The Striped Pajamas.jpeg",
  "The Boy with a Broken Heart": "/BookCoversNew/The Boy With A Broken Heart.jpeg",
  "The Call of the Wild (New)": "/BookCoversNew/The Call Of The Wild.jpeg",
  "The Complete Short Stories": "/BookCoversNew/The Complete Short Stories.jpeg",
  "The Count Of MonteCristo": "/BookCoversNew/The Count Of Monte Cristo.jpeg",
  "The Courage to be Disliked": "/BookCoversNew/The Courage To Be Disliked.jpeg",
  "The DaVinci Code": "/BookCoversNew/The Davinci Code Dan Brown.jpeg",
  "The Day of the Jackal (New)": "/BookCoversNew/The Day Of The Jackal.jpeg",
  "The Extraordinary Miss Sunshine": "/BookCoversNew/The Extraordinary Miss Sunshine.jpeg",
  "The Fisher Queens Dynasty": "/BookCoversNew/The Fisher Queens Dyansty.jpeg",
  "The Forty Five Guardsmen": "/BookCoversNew/The Forty Five Guardsmen.jpeg",
  "The Fox": "/BookCoversNew/The Fox Frederick Forysyth.jpeg",
  "The Gifts of Imperfection": "/BookCoversNew/The Gifts Of Imperfection.jpeg",
  "The Girl I Last Loved": "/BookCoversNew/The Girl I Last Loved Smita Kau.jpeg",
  "The Girl in Room 105": "/BookCoversNew/The Girl In Room 105.jpeg",
  "The Happiness Trap": "/BookCoversNew/The Happiness Trap.jpeg",
  "The House That BJ Built": "/BookCoversNew/The House That BJ Built.jpeg",
  "The Intelligent Investor": "/BookCoversNew/The Intelligent Investor.jpeg",
  "The Jungle Book": "/BookCoversNew/The Jungle Book Nt.jpeg",
  "The Kalam Effect": "/BookCoversNew/PM Nair The Kalam Effect.jpeg",
  "The Little Mermaid": "/BookCoversNew/The Little Mermaid.jpeg",
  "The Lord of the Rings The Fellowship of the Ring": "/BookCoversNew/The Lord Of The Rings 1.jpeg",
  "The Lord of the Rings The Return of the King": "/BookCoversNew/The Lord Of The Rings 3.jpeg",
  "The Lord of the Rings The Two Towers": "/BookCoversNew/The Lord Of The Rings 2.jpeg",
  "The Lost Symbol (New)": "/BookCoversNew/The Lost Symbol.jpeg",
  "The Man Who Saved India": "/BookCoversNew/The Man Who Saved India SARDAR PATEL.jpeg",
  "The Merry Adventures of Robin Hood": "/BookCoversNew/The Merry Adventures Of Robin Hood.jpeg",
  "The Monk who Sold His Ferrari": "/BookCoversNew/The Monk Who Sold His Ferrari Robin S Sharma.jpeg",
  "The Mother I Never Knew": "/BookCoversNew/The Mother I Never Knew.jpeg",
  "The ONE YOU CANNOT HAVE": "/BookCoversNew/The One You Cannot Have.jpeg",
  "The Palace of Illusions": "/BookCoversNew/The Palace Of Illusions.jpeg",
  "The Paradoxical Prime Minister": "/BookCoversNew/The Paradoxical Prime Minister.jpeg",
  "The Pilgrimage (New)": "/BookCoversNew/The Pilgrimage.jpeg",
  "The Promise": "/BookCoversNew/The Promise Nikita Singh.jpeg",
  "The Psychology of Money": "/BookCoversNew/Morgan Housel Psychology of Money.jpeg",
  "The Road Less Traveled": "/BookCoversNew/The Road Less Travelled.jpeg",
  "The Science of Self Healing": "/BookCoversNew/The Science Of Self Healing.jpeg",
  "The Secret": "/BookCoversNew/The Secret.jpeg",
  "The Secret Wish List": "/BookCoversNew/The Secret Wish List.jpeg",
  "The Secret Wishlist": "/BookCoversNew/The Secret Wishlist Preeti Shenoy.jpeg",
  "The Silent Patient by Alex Michaelides": "/BookCoversNew/The Silent Patient.jpeg",
  "The Three Body Problem": "/BookCoversNew/The Three Body Problem.png",
  "The Three Musketeers": "/BookCoversNew/THE THREE MUSKETERS.jpeg",
  "The Wheel of Time": "/BookCoversNew/The Wheel Of Time.jpeg",
  "The Worlds Best Boyfriend": "/BookCoversNew/The World S Best Boyfriend.jpeg",
  "The Zoya Factor": "/BookCoversNew/The Zoya Factor.jpeg",
  "The adventures of Tom Sawyer": "/BookCoversNew/The adventures of Tom bombadil.png",
  "The colossus of rome": "/BookCoversNew/the colossus of rome.jpg",
  "The ritual": "/BookCoversNew/the ritual.jpg",
  "The way of the superior man": "/BookCoversNew/the way of the superior man.jpg",
  "Think Like A Monk": "/BookCoversNew/think like a monk.jpg",
  "Three Mistakes of My Life": "/BookCoversNew/The Mistakes Of My Life.jpeg",
  "Time Stops At Shamli Other Stories": "/BookCoversNew/Time Stops At Shamli.jpeg",
  "Trading Price Action": "/BookCoversNew/Trading Price Action Trading Ranges.jpeg",
  "Very Hungry Caterpillar": "/BookCoversNew/Very Hungry Cterpillar.jpeg",
  "Vladimir Nabokov Lolita": "/BookCoversNew/Vladmir Nabokov Lolita Penguin Modern Classics.jpeg",
  "Wabi Sabi Japanese Wisdom for a Perfectly Imperfect Life": "/BookCoversNew/Wabi Sabi Japanese Wisdom For A Perfectly Imperfect Life.jpeg",
  "When Bad Things Happen to Good People": "/BookCoversNew/When Bad Things Happens To Good People.jpeg",
  "When Dimple Met Rishi": "/BookCoversNew/When Dimple Met Rishi.jpeg",
  "When Only Love Remains (Durjoy Datta)": "/BookCoversNew/When Only Love Remains -Durjoy Datta .jpeg",
  "Will You Still Love Me": "/BookCoversNew/Will You Still Love Me Ravindra Singh.jpeg",
  "Wings Of Fire": "/BookCoversNew/wings of fire.jpg",
  "Wonder": "/BookCoversNew/Wonder.jpeg",
  "World s Best Boyfriend": "/BookCoversNew/World S Best Boyfriend.jpg",
  "You are the Best Wife A True Love Story": "/BookCoversNew/You Are The Best Wife.jpeg",
  "You are the Password of My Life": "/BookCoversNew/You Re The Password Of My Life.jpeg",
  "You are Trending in my Dreams": "/BookCoversNew/You Are Trending In My Dreams Now.jpeg",
  "You Were My Crush Hindi": "/BookCoversNew/You were my crush till you said you love me.jpg",
  "You Were My Crush": "/BookCoversNew/You were my crush till you said you love me.jpg",
  "Your Dreams are Mine Now": "/BookCoversNew/Your Dreams Are Mine Now Novel.jpeg"
};

export function getBookCover(title: string): string {
  const DEFAULT = "/placeholder.svg";
  const sanitize = (path: string | undefined): string => {
    if (!path || typeof path !== 'string') return DEFAULT;
    const lower = path.toLowerCase();
    const validExt = lower.endsWith('.jpg') || lower.endsWith('.jpeg') || lower.endsWith('.png');
    const inDir = lower.startsWith('/bookcoversnew/');
    if (!validExt || !inDir) return DEFAULT;
    return path;
  };
  // Try exact match first
  if (bookCoverMapping[title]) {
    return sanitize(bookCoverMapping[title]);
  }
  
  // Try case-insensitive match
  const lowerTitle = title.toLowerCase();
  const caseInsensitiveMatch = Object.keys(bookCoverMapping).find(
    key => key.toLowerCase() === lowerTitle
  );
  if (caseInsensitiveMatch) {
    return sanitize(bookCoverMapping[caseInsensitiveMatch]);
  }
  
  // Try partial match (first 50 characters)
  const partialMatch = Object.keys(bookCoverMapping).find(
    key => title.includes(key) || key.includes(title)
  );
  if (partialMatch) {
    return sanitize(bookCoverMapping[partialMatch]);
  }
  
  // Return default cover if no match found
  return DEFAULT;
}
