export const bookCoverMapping: Record<string, string> = {
  "10 Ways to Write More Effective Ads": "/BookCoversNew/10 ways to write effective ads.png",
  "100 years of the best American short stories": "/BookCoversNew/100 years of best American stories.png",
  "12Th Fail Hindi Novel": "/BookCoversNew/12th Fail.png",
  "2 States The story of my Marriage": "/BookCoversNew/2 States The Story Of My Marriage.png",
  "50 Stories in English": "/BookCoversNew/50 stories in easy english.png",
  "A Day in the Life": "/BookCoversNew/A Day In The Life Robert Greenfield.jpeg",
  "A Half Baked Love Story": "/BookCoversNew/a half baked love story.jpg",
  "A Little Life": "/BookCoversNew/a little life.jpg",
  "A Second Chance": "/BookCoversNew/a second chance.jpg",
  "A Text Book of Dravyaguna Vijnana": "/BookCoversNew/a textbook of dravyaguna.jpg",
  "A Warrior s Life": "/BookCoversNew/Paulo Caelho A Warrior S Life.jpeg",
  "Accidental Love": "/BookCoversNew/Accidental love.png",
  "Accidentally in Love": "/BookCoversNew/accidentally in love.jpg",
  "Advantage Love": "/BookCoversNew/advantage love.jpg",
  "Adventures of Huckleberry Finn": "/BookCoversNew/adventures of huckleberry fins.jpg",
  "Adventures of Pinocchio": "/BookCoversNew/The Adventures Of Pinocchio.png",
  "Adventures of Tom Bombadil": "/BookCoversNew/The adventures of Tom bombadil.png",
  "Akbar And Birbal": "/BookCoversNew/Akbar Aur Birbal.jpeg",
  "Albert Einstein": "/BookCoversNew/Albert Einstein.jpg",
  "Allen B Tucker Computer Science and Engineering Handbook": "/BookCoversNew/second edition computer science handbook.jpg",
  "American Folk Tales": "/BookCoversNew/american folktales.jpg",
  "American Short Stories": "/BookCoversNew/American short stories.jpg",
  "An Introduction To Buddhism": "/BookCoversNew/An Introduction To Buddhism.jpg",
  "An Unexpected Gift": "/BookCoversNew/An Unexpected Gift.jpg",
  "Angels Demons": "/BookCoversNew/Angels and demons.png",
  "Art Of Drawing The Human Body": "/BookCoversNew/Small Size Drawing The Human Body.jpeg",
  "Atomic Habits": "/BookCoversNew/atomic habits.jpg",
  "Attitude is Everything": "/BookCoversNew/Attitude Is Everything.jpg",
  "Ayurveda The Divine Science": "/BookCoversNew/Ayurveda Divine Science Of Life.jpg",
  "Bared to You": "/BookCoversNew/bared to you.jpg",
  "Becoming Your Best Self": "/BookCoversNew/Becoming your best self.jpg",
  "Bhagavad Gita Hindi": "/BookCoversNew/Bhagavad Gita Hindi.png",
  "Can Love Happen Twice": "/BookCoversNew/can love happen twice.jpg",
  "Charitraheen": "/BookCoversNew/charitraheen.jpg",
  "Chicot the Jester": "/BookCoversNew/Chicot the jester.png",
  "Chikitsa Sutra": "/BookCoversNew/chikitsa sutra.jpg",
  "Complete Sherlock Holmes 1960": "/BookCoversNew/The Complete Short Stories.jpeg",
  "CORONAVIRUS": "/BookCoversNew/coronavirus.jpg",
  "Crime and Punishment": "/BookCoversNew/crime and punishment.jpg",
  "Dan Brown Origin": "/BookCoversNew/Dan Brown Origin.jpg",
  "Dear God What s Happening to Us": "/BookCoversNew/Lynn Grabhorn Dear God What S Happening To Us.jpeg",
  "Do Kadam Aur Sahi": "/BookCoversNew/DO Kadam Aur Sahi.png",
  "Don t Feed the Monkey Mind": "/BookCoversNew/Don T Feed The Monkey Mind.jpg",
  "Drawing Cartoons and Comics for Dummies PDF": "/BookCoversNew/drawing cartoons and comics for dummies.jpg",
  "Ego is the Enemy": "/BookCoversNew/ego is the enemy.jpg",
  "Eleven Minutes": "/BookCoversNew/Eleven minutes.png",
  "Elmer s Friends": "/BookCoversNew/elmers friend.jpg",
  "Elmers s Special Day": "/BookCoversNew/elmers special day.jpg",
  "Emotional Intelligence": "/BookCoversNew/Emotional Intelligence.jpg",
  "English Fairy Tales and More English Fairy Tales": "/BookCoversNew/English Fairy tales.png",
  "English Short Stories": "/BookCoversNew/American short stories.jpg",
  "Essentials of Medical Microbiology": "/BookCoversNew/Essentials of Microbiology.png",
  "Essentials of Pharmacoeconomics": "/BookCoversNew/Essentials Of Pharmacoeconomics.jpg",
  "Fables and Stories": "/BookCoversNew/fables and stories.jpg",
  "Feeling Good": "/BookCoversNew/feeling good.jpg",
  "Few Things Left Unsaid": "/BookCoversNew/few things left unsaid.jpg",
  "Finish What You Start": "/BookCoversNew/Finish what you start.jpg",
  "First We Make the Beast Beautiful": "/BookCoversNew/First We Make The Beast Beautiful.jpg",
  "Franny and Zooey": "/BookCoversNew/Franny and Zooey.png",
  "Genius Foods": "/BookCoversNew/genius foods.jpg",
  "Get Epic Shit Done": "/BookCoversNew/get epic shit done.jpg",
  "Give and Take": "/BookCoversNew/give and take.jpg",
  "Gone Girl": "/BookCoversNew/Gone Girl.jpg",
  "Grandma s Bag of Stories": "/BookCoversNew/Grandma S Bag Of Stories.jpg",
  "Guide to Competetive Programming": "/BookCoversNew/Guide to Competitive Programming.png",
  "Henry and Mudge and Annie Good Move": "/BookCoversNew/Henry And Mudge And Annie S Good Move.png",
  "Henry and Mudge and Annie Perfect Pet": "/BookCoversNew/Henry And Mudge Annie S Perfect Pet.png",
  "Henry and Mudge and Mrs Hopper House": "/BookCoversNew/Henry And Mudge Mr Hopper S House.png",
  "Henry and Mudge and the Bedtime Thumps": "/BookCoversNew/Henry and Mudge and the bedtime thums.png",
  "Henry and Mudge and the Big Sleepover": "/BookCoversNew/Henry and Mudge and a big sleepover.png",
  "Henry and Mudge and the Careful Cousin": "/BookCoversNew/Henry and Mudge and the careful cousin.png",
  "Henry and Mudge and the Forever Sea": "/BookCoversNew/Henry and Mudge and the forever sea.png",
  "Henry and Mudge and the Great Grandpas": "/BookCoversNew/Henry and Mudge and the great grandpa.png",
  "Henry and Mudge and the Happy Cat": "/BookCoversNew/Henry and Mudge and the happy cat.png",
  "Henry and Mudge and the Long Weekend": "/BookCoversNew/Henry and Mudge and the long weekend.png",
  "Henry and Mudge and the Sneaky Crackers": "/BookCoversNew/Henry and Mudge and sneaky crackers.png",
  "Henry and Mudge and the Snowman Plan": "/BookCoversNew/Henry And Mudge And The Snowman Plan.png",
  "Henry and Mudge and the Starry Night May": "/BookCoversNew/Henry and Mudge and the starry night.png",
  "Henry and Mudge and the Tall Tree House": "/BookCoversNew/Henry and Mudge and the tall tree house.png",
  "Henry and Mudge and the Tumbling Trip": "/BookCoversNew/Henry and Mudge and the tumbling trip.png",
  "Henry and Mudge and the Wild Goose Chase": "/BookCoversNew/Henry and Mudge and the wild goose.png",
  "Henry and Mudge and the Wild Wind": "/BookCoversNew/Henry and Mudge and the wild wind.png",
  "Henry and Mudge Get the Cold Shivers": "/BookCoversNew/Henry and Mudge and the cold shivers.png",
  "Henry and Mudge in Puddle Trouble": "/BookCoversNew/Henry and Mudge in puddle trouble.png",
  "Henry and Mudge in the Family Trees": "/BookCoversNew/Henry and Mudge in the green time.png",
  "Henry and Mudge in the Green Time": "/BookCoversNew/Henry and Mudge in the green time.png",
  "Henry and Mudge in the Sparkle Days": "/BookCoversNew/Henry and Mudge in the sparkle days.png",
  "Henry and Mudge Take the Big Test": "/BookCoversNew/Henry and Mudge take the big test.png",
  "Henry and Mudge The First Book of Their Adventures": "/BookCoversNew/Henry and Mudge the first book.png",
  "Henry and Mudge Under the Yellow Moon": "/BookCoversNew/Henry and Mudge under the yellow moon.png",
  "HOLD MY HAND": "/BookCoversNew/hold my hand(1).jpg",
  "House of Cards": "/BookCoversNew/house of cards.jpg",
  "How I Topped The UPSC and How You Can Too": "/BookCoversNew/how I topped the upsc.jpg",
  "How To Analyze People": "/BookCoversNew/How To Analyse People.jpg",
  "How to Become a Straight A Student": "/BookCoversNew/How To Become A Straight A Student.jpg",
  "How to Read People Like a Book": "/BookCoversNew/how to read people like a book.jpg",
  "How to Talk to Anyone 92 Little Tricks for Big Success": "/BookCoversNew/How To Talk To Anyone 92 Trick.jpg",
  "How to Win Every Argument": "/BookCoversNew/How To Win Every Argument.jpg",
  "I Too had a Love Story": "/BookCoversNew/I Too Had A Love Story.jpg",
  "If It s Not Forever": "/BookCoversNew/If It S Not Forever, It S Not Love.jpg",
  "India that is Bharat": "/BookCoversNew/India That Is Bharat.jpg",
  "Inferno": "/BookCoversNew/inferno.jpg",
  "It Happens for a Reason": "/BookCoversNew/It happens for a reason.jpg",
  "It s Not How Good You Are It s How Good You Want to Be": "/BookCoversNew/It S Not How Good You Are, It S How Good You Want To Be.jpg",
  "It Started with a Friend Request": "/BookCoversNew/It Started With A Friend Request.jpg",
  "Its All In The Planets": "/BookCoversNew/It S All In The Planets.png",
  "Julius Caesar The Colossus of Rome": "/BookCoversNew/the colossus of rome.jpg",
  "Katie In Love": "/BookCoversNew/Katie in love.jpg",
  "Konark Hindi Novel": "/BookCoversNew/Konark.png",
  "Life is a Soap Bubble": "/BookCoversNew/Life of A Soap Bubble.png",
  "Life Is What You Make It": "/BookCoversNew/life is what you make it.jpg",
  "Like It Happened Yesterday": "/BookCoversNew/Like It Happened Yesterday.jpg",
  "Long Walk to Freedom": "/BookCoversNew/Long Walk To Freedom The Autobigraphy.jpeg",
  "Lord Of The Rings The Return Of The King": "/BookCoversNew/The Lord Of The Rings 1.jpeg",
  "Losing My Virginity and Other Dumb Ideas": "/BookCoversNew/Losing My Virginity And All Other Dares.jpeg",
  "love facebook": "/BookCoversNew/Love@facebook.jpeg",
  "Love Kisses And All Things Warm": "/BookCoversNew/Love Kisses And All Things Warm.jpeg",
  "Mahabharat": "/BookCoversNew/Mahabharat Hindi.jpeg",
  "Mahabharata Veda Vyasa eng": "/BookCoversNew/Mahabharat Ved Vyas.jpeg",
  "Mahayoddha Kalki Sword of Shiva": "/BookCoversNew/Mahayoddha Kalki Sword Of Shiva.jpeg",
  "Michael Jordan A Biography": "/BookCoversNew/Michael Jordan A Biography.jpeg",
  "Microprocessors Microcontroller Systems": "/BookCoversNew/microprocessor and microcontroller system.jpg",
  "Midnights Children by Salman Rushdie": "/BookCoversNew/Midnights Children By Salman Rushdie.jpeg",
  "Mistakes Like Love and Sex": "/BookCoversNew/Mistakes Like Love And Sex.jpeg",
  "Modern Arabic Short Stories": "/BookCoversNew/Modern Arabic Short Stories.jpeg",
  "Moonwalking with Einstein": "/BookCoversNew/Moonwalking With Einstein.jpeg",
  "Mother Teresa A Biography": "/BookCoversNew/Mother Teresa A Biography.jpeg",
  "My Clingy Girlfriend": "/BookCoversNew/My Clingy Girlfriend Madhuri.jpeg",
  "Mystery Short Stories": "/BookCoversNew/Mystery Short Stories.jpeg",
  "Napoleon A Biography": "/BookCoversNew/Napolean A Biography.jpeg",
  "Narendra Modi A Political Biography": "/BookCoversNew/Narendra Modi A Political Biography.jpeg",
  "Nelson Mandela A Biography": "/BookCoversNew/Nelson Mandela A Biography.jpeg",
  "Of Course I Love You": "/BookCoversNew/Of Course I Love You Till I Found Someone Better.jpeg",
  "Oh Yes I m Single": "/BookCoversNew/Oh Yes I M Single, And So Is My Girlfriend.jpg",
  "Oliver Twist": "/BookCoversNew/Oliver Twist.jpeg",
  "One Arranged Murder": "/BookCoversNew/One Arranged Murder.jpeg",
  "One Hundred Years Of Solitude": "/BookCoversNew/One Hundred Years Of Soltitude.jpeg",
  "One Indian Girl": "/BookCoversNew/One Indian Girl Chetan Bhagat.jpeg",
  "One Night at The Call Center": "/BookCoversNew/One night at the call center.png",
  "Our IMPossible Love": "/BookCoversNew/our impossible love.jpg",
  "Our Story Needs No Filter": "/BookCoversNew/Our Story Needs No Filter Sudeep.jpeg",
  "Outsiders American Short Stories for students of ESL": "/BookCoversNew/Outsiders American Short Stories for students of esl.jpeg",
  "Percy Jackson and The Battle of the Labyrinth": "/BookCoversNew/Percy Jackson And The Battle Of The Labyrimin.jpeg",
  "Percy Jackson and The Last Olympian": "/BookCoversNew/Percy Jackson And The Last Olympian.jpeg",
  "Percy Jackson and The Lightning Thief": "/BookCoversNew/Percy Jackson And The Lightning Thief.jpeg",
  "Percy Jackson and The Sea of Monsters": "/BookCoversNew/Percy Jackson And The Sea Of Monsters.jpeg",
  "Percy Jackson and The Titan s Curse": "/BookCoversNew/Percy Jackson And The Titan S Curse.jpeg",
  "Picture Dictionary": "/BookCoversNew/Picture Dictionary Longman Children.jpeg",
  "Prem Purana Mythological Love Stories": "/BookCoversNew/Prem Purana Mythological Love Stories.jpeg",
  "Presentation Secrets Of Steve Jobs": "/BookCoversNew/Presentation Secets Of Steve Jobs.jpeg",
  "Python API Development Fundamentals": "/BookCoversNew/Python API Deevelopment Fundamentals.jpeg",
  "Reasons to Stay Alive": "/BookCoversNew/Reasons To Stay Alive Matt Haig.jpeg",
  "Rebecca": "/BookCoversNew/Rebecca.jpeg",
  "Reconsidering REDD Authority Power and Law": "/BookCoversNew/Reconsidering Redd+ Authority Ananya Sharma.jpeg",
  "Reflections Of A Man": "/BookCoversNew/Reflections Of A Man Amari Soul.jpeg",
  "Religious Therapeutics": "/BookCoversNew/Religious Therapeutics Body.jpeg",
  "Revolution 2020": "/BookCoversNew/Revolution 2020 Chetan Bhagat.jpeg",
  "Rich Dads Increase Your Financial IQ Get Smarter with Your Money": "/BookCoversNew/Rich Dads Increase Your Financial IQ.jpeg",
  "Right Here Right Now": "/BookCoversNew/Right Here Right Now Nikita Singh.jpeg",
  "Robinson Crusoe": "/BookCoversNew/Robinson Crusoe.jpeg",
  "Ruk Jaana Nahin": "/BookCoversNew/Ruk Jaana Nahin Nishant Jain.jpeg",
  "Sacred Games": "/BookCoversNew/Sacred Games A Novel.jpeg",
  "Saket": "/BookCoversNew/Saket.png",
  "Satyayoddha Kalki Eye of Brahma": "/BookCoversNew/Satyayoddha Kalki Eye Of Brahma.jpeg",
  "Selected Short Stories": "/BookCoversNew/100 Selected Short Stories.jpeg",
  "Self Liberation From Fear Worry and Angry": "/BookCoversNew/Self Liberation from Fear,Worry and Angry.png",
  "She Broke Up I Didn t": "/BookCoversNew/She Broke Up I Didn T I Just Kissed.jpeg",
  "Short stories English": "/BookCoversNew/Short Stories English.jpeg",
  "Short Stories for Children for Spoken English": "/BookCoversNew/Short Stories For Children For Spoken English Practice.jpeg",
  "Short Stories For Children": "/BookCoversNew/Short Stories For Children For Spoken English Practice.jpeg",
  "Short Stories for English Courses": "/BookCoversNew/Short Stories For English Courses.jpeg",
  "Short Stories of The Day": "/BookCoversNew/SHORT STORIES.jpeg",
  "SHORT STORIES": "/BookCoversNew/100 Selected Short Stories.jpeg",
  "Short-Stories": "/BookCoversNew/100 Selected Short Stories.jpeg",
  "Shri Ramcharitmanas Hindi": "/BookCoversNew/Shri Ramcharitramanas (Hindi).jpeg",
  "Shutter Island": "/BookCoversNew/Shutter Island.jpeg",
  "Soma in Yoga and Ayurveda": "/BookCoversNew/Soma in Yoga and Ayurveda.jpeg",
  "Someone Like You": "/BookCoversNew/Someone Like You Durjoy Datta.jpeg",
  "Something I Never Told You": "/BookCoversNew/Something I Never Told You.jpeg",
  "Sorry You are Not My Type": "/BookCoversNew/sorry you are not my type.jpeg",
  "Spanish Short Stories For Beginners": "/BookCoversNew/Spanish Short Stories For Beginners.jpeg",
  "Sri Ramcharitmanas English": "/BookCoversNew/Shri Ramcharitramanas (Hindi).jpeg",
  "Steal the Show": "/BookCoversNew/Steal the show for speeches to stage.jpeg",
  "Stop Overthinking": "/BookCoversNew/Stop Overthinking.jpg",
  "Stories from PANCHATANTRA": "/BookCoversNew/Stories Of Panchatantra.jpeg",
  "Story Craft": "/BookCoversNew/STORYCRAFT The Complete Guide to Storytelling.jpeg",
  "Super Immunity": "/BookCoversNew/Super Immunity The Essential Nutrition.jpeg",
  "Swadeshi Chikitsa": "/BookCoversNew/SwadeshiChikitsa Vol 1.jpeg",
  "Sweet Nothings": "/BookCoversNew/Sweet Nothings.jpeg",
  "Sweet Sixteen": "/BookCoversNew/Sweet Sixteen.jpeg",
  "Tea for Two and a Piece of Cake": "/BookCoversNew/Tea For Two And A Piece Of Cake Sudeep Menon.jpeg",
  "Tell The Last Breath": "/BookCoversNew/Till The Last Breath.jpeg",
  "Ten Years Later": "/BookCoversNew/Ten Years Later.jpeg",
  "Textbook of Ayurveda": "/BookCoversNew/Textbook of Ayurveda.jpeg",
  "Thats The Way We Met": "/BookCoversNew/That S The Way We Met Sudeep Menon.jpeg",
  "The 3 Three Mistakes of My Life": "/BookCoversNew/The Mistakes Of My Life.jpeg",
  "The 5 Second Rule": "/BookCoversNew/Mel Robbins The 5 Second Rule.jpeg",
  "The 5AM Club": "/BookCoversNew/The 5 Am Club Robin Sharma.jpeg",
  "The adventures of Tom Sawyer": "/BookCoversNew/The adventures of Tom bombadil.png",
  "The Alchemist": "/BookCoversNew/Paulo Caelho The Alchemist (1993).jpeg",
  "The Anxiety and Phobia Workbook": "/BookCoversNew/The Anxiety And Phobia Workbook.jpeg",
  "The Art of Public Speaking": "/BookCoversNew/The Art Of Public Speaking.png",
  "The Bhagavad Gita": "/BookCoversNew/The Bhagavad Gita A Biography.jpeg",
  "The Boy in The Striped Pajamas": "/BookCoversNew/The Boy In The Striped Pajamas.jpeg",
  "The Boy with a Broken Heart": "/BookCoversNew/The Boy With A Broken Heart.jpeg",
  "The Call of the Wild": "/BookCoversNew/The Call Of The Wild.jpeg",
  "The Complete Short Stories": "/BookCoversNew/The Complete Short Stories.jpeg",
  "The Count Of MonteCristo": "/BookCoversNew/The Count Of Monte Cristo.jpeg",
  "The Courage to be Disliked": "/BookCoversNew/The Courage To Be Disliked.jpeg",
  "The DaVinci Code": "/BookCoversNew/The Davinci Code Dan Brown.jpeg",
  "The Day of the Jackal": "/BookCoversNew/The Day Of The Jackal.jpeg",
  "The Extraordinary Miss Sunshine": "/BookCoversNew/The Extraordinary Miss Sunshine.jpeg",
  "The Fisher Queens Dynasty": "/BookCoversNew/The Fisher Queens Dyansty.jpeg",
  "The Forty Five Guardsmen": "/BookCoversNew/The Forty Five Guardsmen.jpeg",
  "The Fox": "/BookCoversNew/The Fox Frederick Forysyth.jpeg",
  "The Gifts of Imperfection": "/BookCoversNew/The Gifts Of Imperfection.jpeg",
  "The Girl I Last Loved": "/BookCoversNew/The Girl I Last Loved Smita Kau.jpeg",
  "The Girl in Room 105": "/BookCoversNew/The Girl In Room 105.jpeg",
  "The Happiness Trap": "/BookCoversNew/The Happiness Trap.jpeg",
  "The House That BJ Built": "/BookCoversNew/The House That BJ Built.jpeg",
  "The Intelligent Investor": "/BookCoversNew/The Intelligent Investor.jpeg",
  "The Jungle Book": "/BookCoversNew/The Jungle Book Nt.jpeg",
  "The Kalam Effect": "/BookCoversNew/PM Nair The Kalam Effect.jpeg",
  "The Little Mermaid": "/BookCoversNew/The Little Mermaid.jpeg",
  "The Lord of the Rings The Fellowship of the Ring": "/BookCoversNew/The Lord Of The Rings 1.jpeg",
  "The Lord of the Rings The Two Towers": "/BookCoversNew/The Lord Of The Rings 1.jpeg",
  "The Lost Symbol": "/BookCoversNew/The Lost Symbol.jpeg",
  "The Man Who Saved India": "/BookCoversNew/The Man Who Saved India SARDAR PATEL.jpeg",
  "The Merry Adventures of Robin Hood": "/BookCoversNew/The Merry Adventures Of Robin Hood.jpeg",
  "The Monk who Sold His Ferrari": "/BookCoversNew/The Monk Who Sold His Ferrari Robin S Sharma.jpeg",
  "The Mother I Never Knew": "/BookCoversNew/The Mother I Never Knew.jpeg",
  "THE ONE YOU CANNOT HAVE": "/BookCoversNew/The One You Cannot Have Preti Shenoy.jpeg",
  "The Palace of Illusions": "/BookCoversNew/The Palace Of Illusions.jpeg",
  "The Paradoxical Prime Minister": "/BookCoversNew/The Paradoxical Prime Minister.jpeg",
  "The Pilgrimage": "/BookCoversNew/The Pilgrimage.jpeg",
  "The Promise": "/BookCoversNew/The Promise Nikita Singh.jpeg",
  "The Ritual": "/BookCoversNew/the ritual.jpg",
  "The Road Less Traveled": "/BookCoversNew/The Road Less Travelled.jpeg",
  "The Science of Self Healing": "/BookCoversNew/The Science Of Self Healing.jpeg",
  "The Secret Wish List": "/BookCoversNew/The Secret Wish List.jpeg",
  "The Secret Wishlist": "/BookCoversNew/The Secret Wish List.jpeg",
  "The Secret": "/BookCoversNew/The Secret Wish List.jpeg",
  "The Silent Patient by Alex Michaelides": "/BookCoversNew/The Silent Patient.jpeg",
  "The Theory of Everything": "/BookCoversNew/Stephen W Hawking The Theory Of Everything.jpeg",
  "The Three Body Problem": "/BookCoversNew/The Three Body Problem.png",
  "The Three Musketeers": "/BookCoversNew/THE THREE MUSKETERS.jpeg",
  "The Way of the Superior Man": "/BookCoversNew/the way of the superior man.jpg",
  "The Wheel of Time": "/BookCoversNew/The Wheel Of Time.jpeg",
  "The Worlds Best Boyfriend": "/BookCoversNew/The World S Best Boyfriend.jpeg",
  "The Zoya Factor": "/BookCoversNew/The Zoya Factor.jpeg",
  "Think Like A Monk": "/BookCoversNew/think like a monk.jpg",
  "This Love that Feels Right": "/BookCoversNew/This Love That Feels Right.jpeg",
  "Three Ghost Stories": "/BookCoversNew/Three Ghost Stories.jpeg",
  "Three Mistakes of My Life": "/BookCoversNew/Th 3 (Three) Mistakes Of My Life Chetan Bhagat.jpeg",
  "Till The Last Breath": "/BookCoversNew/Till The Last Breath.jpeg",
  "Time Stops At Shamli Other Stories": "/BookCoversNew/Time Stops At Shamli.jpeg",
  "Trade and Grow Rich": "/BookCoversNew/Trade And Grow Rich.jpeg",
  "Trading Price Action": "/BookCoversNew/Trading Price Action Trading Ranges.jpeg",
  "Universal Magick": "/BookCoversNew/Universal Magick.jpeg",
  "Veronika Decides to Die": "/BookCoversNew/Veronika Decides To Die.jpeg",
  "Very Hungry Caterpillar": "/BookCoversNew/Very Hungry Cterpillar.jpeg",
  "Vicomte de Bragelonne": "/BookCoversNew/Vicomte De Bragelonne.jpeg",
  "Wabi Sabi Japanese Wisdom for a Perfectly Imperfect Life": "/BookCoversNew/Wabi Sabi Japanese Wisdom For A Perfectly Imperfect Life.jpeg",
  "What is Death": "/BookCoversNew/What Is Death.jpeg",
  "When Bad Things Happen to Good People": "/BookCoversNew/When Bad Things Happens To Good People.jpeg",
  "When Dimple Met Rishi": "/BookCoversNew/When Dimple Met Rishi.jpeg",
  "When Only Love Remains": "/BookCoversNew/When Only Love Remains -Durjoy Datta .jpeg",
  "Wilde Oscar Short Stories": "/BookCoversNew/Wilde Oscar Short Stories.jpeg",
  "Will You Still Love Me By Ravinder Singh": "/BookCoversNew/Will You Still Love Me Ravindra Singh.jpeg",
  "Wings Of Fire": "/BookCoversNew/Wings of fire.jpg",
  "Winning Habits": "/BookCoversNew/winning habits.jpg",
  "Wonder": "/BookCoversNew/Wonder.jpeg",
  "World s Best Boyfriend": "/BookCoversNew/The World S Best Boyfriend.jpeg",
  "You are the Best Wife A True Love Story": "/BookCoversNew/You Are The Best Wife.jpeg",
  "You are the Password of My Life": "/BookCoversNew/You Re The Password Of My Life.jpeg",
  "You are Trending in my Dreams": "/BookCoversNew/You Are Trending In My Dreams Now.jpeg",
  "You Were My Crush Hindi": "/BookCoversNew/tum meru crush ho.jpg",
  "You Were My Crush Till You Said You Love Me": "/BookCoversNew/You were my crush till you said you love me.jpg",
  "You Were My Crush": "/BookCoversNew/You Were My Crush Till You Said Durjoy Datta.jpeg",
  "Your Dreams are Mine Now": "/BookCoversNew/Your Dreams Are Mine Now Novel.jpeg",
  "यन फरडम परयवरण और आतम नरभरत": "/BookCoversNew/Unn Freedom,Paryavaran And Atma Bharat.jpeg",
  "10 Books in 1": "/BookCoversNew/Ten books in one.png",
  "Ayurveda Treatment for Beginner": "/BookCoversNew/Textbook of Ayurveda.jpeg",
  "Biography of Charlie Chaplin": "/BookCoversNew/Charlie Chaplin S Biography.png",
  "Biography of Swami Vivekananda": "/BookCoversNew/Swami vivekananda biography.png",
  "Buddhas Brain The Practical Neuroscience": "/BookCoversNew/Buddha S Brain.jpg",
  "Do Bailo Ki Katha": "/BookCoversNew/दो बैलों की कथा.png",
  "Five Point Someone": "/BookCoversNew/5 points someone what not to do at iit.jpg",
  "Fundamental Theories of Physics": "/BookCoversNew/Black Hole Physics.jpg",
  "Hotel by Arthur Hailey": "/BookCoversNew/hotel.jpg",
  "Legal Eagles Stories of the Top Seven Indian Lawyers": "/BookCoversNew/legal eagles.jpg",
  "Marry Poppins": "/BookCoversNew/Mary poppins 1967.jpeg",
  "Now That You are Rich": "/BookCoversNew/Now That You Re Rich, Let S Fall In Love.jpg",
  "Scion of Ikshvaku": "/BookCoversNew/Scian Of Ikshvaku Ram Chandra.jpeg",
  "Stories From My Teacher": "/BookCoversNew/Stories Of Panchatantra.jpeg",
  "The Girls Of My Dreams": "/BookCoversNew/pingpdf.com The girl of my dreams.jpeg",
  "The Psychology of Money": "/BookCoversNew/Morgan Housel Psychology of Money.jpeg",
  "Unn Freedom,Paryavaran And Atma Bharat": "/BookCoversNew/यन फरडम परयवरण और आतम नरभरत.png",
  "Vladimir Nabokov Lolita": "/BookCoversNew/Vladmir Nabokov Lolita Penguin Modern Classics.jpeg",
  "Frankenstein or The Mordern Prometheus": "/BookCoversNew/the ritual.jpg",
  "Harry Potter and the Chamber of Secrets": "/BookCoversNew/Harry Potter And The Chamber Of Secrets.jpg",
  "Harry Potter and the Deathly Hallows": "/BookCoversNew/Harry Potter and the deathly hallows.jpg",
  "Harry Potter and the Goblet of FIre": "/BookCoversNew/Harry Potter and the goblet of fire.jpg",
  "Harry Potter and the Half Blood Prince": "/BookCoversNew/Harry Potter and the half blood prince.jpg",
  "Harry Potter and the Philosophers Stone": "/BookCoversNew/Harry Potter and the sorcerers stone.jpg",
  "Harry Potter and the Prisoner of Azkaban": "/BookCoversNew/Harry Potter and the prisoner of azkaban.jpg",
  "Harry Potter Complete Collection": "/BookCoversNew/Harry Potter Complete Collection.jpg"
};

export function getBookCover(title: string): string {
  const DEFAULT = "/placeholder.svg";
  const sanitize = (path: string | undefined): string => {
    if (!path || typeof path !== 'string') return DEFAULT;
    const lower = path.toLowerCase();
    const validExt = lower.endsWith('.jpg') || lower.endsWith('.jpeg') || lower.endsWith('.png');
    const inDir = lower.startsWith('/bookcoversnew/');
    if (!validExt || !inDir) return DEFAULT;
    return path;
  };
  // Try exact match first
  if (bookCoverMapping[title]) {
    return sanitize(bookCoverMapping[title]);
  }

  // Try case-insensitive match
  const lowerTitle = title.toLowerCase();
  const caseInsensitiveMatch = Object.keys(bookCoverMapping).find(
    key => key.toLowerCase() === lowerTitle
  );
  if (caseInsensitiveMatch) {
    return sanitize(bookCoverMapping[caseInsensitiveMatch]);
  }

  // Try partial match (first 50 characters)
  const partialMatch = Object.keys(bookCoverMapping).find(
    key => title.includes(key) || key.includes(title)
  );
  if (partialMatch) {
    return sanitize(bookCoverMapping[partialMatch]);
  }

  // Return default cover if no match found
  return DEFAULT;
}
