// Auto-generated book cover mapping
// Generated on: 2025-10-31T09:58:50.118Z
// Total covers mapped: 341

/**
 * Map of book titles to cover image paths
 */
export const bookCoverMap: Record<string, string> = {
  "A Second Chance": "/BookCoversNew/a second chance.jpg",
  "Adventures of Pinocchio": "/BookCoversNew/The Adventures Of Pinocchio.png",
  "Albert Einstein": "/BookCoversNew/Albert Einstein.jpg",
  "american short stories": "/BookCoversNew/American short stories.jpg",
  "Angels  Demons": "/BookCoversNew/Angels and demons.png",
  "Bared to You": "/BookCoversNew/bared to you.jpg",
  "Becoming Your Best Self": "/BookCoversNew/Becoming your best self.jpg",
  "Chicot the Jester": "/BookCoversNew/Chicot the jester.png",
  "dan brown   origin": "/BookCoversNew/Dan Brown Origin.jpg",
  "eleven minutes": "/BookCoversNew/Eleven minutes.png",
  "fables and stories": "/BookCoversNew/fables and stories.jpg",
  "Gone Girl": "/BookCoversNew/Gone Girl.jpg",
  "How to Become a Straight A Student": "/BookCoversNew/How To Become A Straight A Student.jpg",
  "Like It Happened Yesterday": "/BookCoversNew/Like It Happened Yesterday.jpg",
  "Michael Jordan A Biography": "/BookCoversNew/Michael Jordan A Biography.jpeg",
  "Midnights children by Salman Rushdie ()": "/BookCoversNew/Midnights Children By Salman Rushdie.jpeg",
  "Mother Teresa   A Biography": "/BookCoversNew/Mother Teresa A Biography.jpeg",
  "mystery short stories": "/BookCoversNew/Mystery Short Stories.jpeg",
  "Narendra Modi A Political Biography": "/BookCoversNew/Narendra Modi A Political Biography.jpeg",
  "Nelson Mandela A Biography": "/BookCoversNew/Nelson Mandela A Biography.jpeg",
  "Of Course I Love You": "/BookCoversNew/of course I love you.jpg",
  "Oliver Twist": "/BookCoversNew/Oliver Twist.jpeg",
  "One Night at call center by Chetan Bhagat": "/BookCoversNew/One Night At Call Center Chetan Bhagat.jpeg",
  "One Indian Girl   Chetan Bhagat": "/BookCoversNew/One Indian Girl Chetan Bhagat.jpeg",
  "Outsiders. American Short Stories for students of ESL": "/BookCoversNew/Outsiders American Short Stories for students of esl.jpeg",
  "Percy Jackson and The Last Olympian": "/BookCoversNew/Percy Jackson And The Last Olympian.jpeg",
  "Percy Jackson and The Lightning Thief": "/BookCoversNew/Percy Jackson And The Lightning Thief.jpeg",
  "Percy Jackson and The Sea of Monsters": "/BookCoversNew/Percy Jackson And The Sea Of Monsters.jpeg",
  "Percy Jackson and The Titan s Curse": "/BookCoversNew/Percy Jackson And The Titan S Curse.jpeg",
  "Prem Purana  Mythological Love Stories": "/BookCoversNew/Prem Purana Mythological Love Stories.jpeg",
  "Rebecca": "/BookCoversNew/Rebecca.jpeg",
  "Reflections Of A Man   Amari Soul": "/BookCoversNew/Reflections Of A Man Amari Soul.jpeg",
  "Religious Therapeutics Body": "/BookCoversNew/Religious Therapeutics Body.jpeg",
  "revolution 2020 by chetan bhagat": "/BookCoversNew/Revolution 2020 Chetan Bhagat.jpeg",
  "Robinson Crusoe": "/BookCoversNew/Robinson Crusoe.jpeg",
  "Ruk Jaana Nahin   Nishant Jain": "/BookCoversNew/Ruk Jaana Nahin Nishant Jain.jpeg",
  "Sacred Games  A Novel": "/BookCoversNew/Sacred Games A Novel.jpeg",
  "Selected Short Stories": "/BookCoversNew/Selected Short Stories.jpeg",
  "short stories english": "/BookCoversNew/Short Stories English.jpeg",
  "short stories for english courses": "/BookCoversNew/Short Stories For English Courses.jpeg",
  "Short Stories": "/BookCoversNew/SHORT STORIES.jpeg",
  "Shutter Island": "/BookCoversNew/Shutter Island.jpeg",
  "small size drawing the human body": "/BookCoversNew/Small Size Drawing The Human Body.jpeg",
  "Soma in Yoga and Ayurveda": "/BookCoversNew/Soma in Yoga and Ayurveda.jpeg",
  "Someone Like You": "/BookCoversNew/Someone Like You.jpg",
  "Spanish Short Stories For Beginners": "/BookCoversNew/Spanish Short Stories For Beginners.jpeg",
  "stories  198": "/BookCoversNew/Stories 198.jpeg",
  "STORIES": "/BookCoversNew/stories.jpeg",
  "Sweet nothings": "/BookCoversNew/Sweet Nothings.jpeg",
  "sweet sixteen": "/BookCoversNew/Sweet Sixteen.jpeg",
  "Ten Years Later": "/BookCoversNew/Ten Years Later.jpeg",
  "Textbook of Ayurveda": "/BookCoversNew/Textbook of Ayurveda.jpeg",
  "The Bhagavad Gita A Biography": "/BookCoversNew/The Bhagavad Gita A Biography.jpeg",
  "The Call of the Wild": "/BookCoversNew/The Call Of The Wild.jpeg",
  "The Complete Short Stories": "/BookCoversNew/The Complete Short Stories.jpeg",
  "The DaVinci Code by Dan Brown": "/BookCoversNew/The Davinci Code Dan Brown.jpeg",
  "The Day of the Jackal": "/BookCoversNew/The Day Of The Jackal.jpeg",
  "The Extraordinary Miss Sunshine": "/BookCoversNew/The Extraordinary Miss Sunshine.jpeg",
  "The Forty Five Guardsmen": "/BookCoversNew/The Forty Five Guardsmen.jpeg",
  "The House That BJ Built": "/BookCoversNew/The House That BJ Built.jpeg",
  "The Little Mermaid": "/BookCoversNew/The Little Mermaid.jpeg",
  "The Lost Symbol": "/BookCoversNew/The Lost Symbol.jpeg",
  "The Palace of Illusions": "/BookCoversNew/The Palace Of Illusions.jpeg",
  "The Zoya Factor": "/BookCoversNew/The Zoya Factor.jpeg",
  "The Jungle Book NT": "/BookCoversNew/The Jungle Book Nt.jpeg",
  "The Pilgrimage": "/BookCoversNew/The Pilgrimage.jpeg",
  "The Science of Self Healing": "/BookCoversNew/The Science Of Self Healing.jpeg",
  "The Secret Wishlist by Preeti shenoy": "/BookCoversNew/The Secret Wishlist Preeti Shenoy.jpeg",
  "Three mistakes of my life  Chetan Bhagat": "/BookCoversNew/Three Mistakes Of My Life Chetan Bhagat.jpeg",
  "Trade and Grow Rich": "/BookCoversNew/Trade And Grow Rich.jpeg",
  "Vicomte de Bragelonne": "/BookCoversNew/Vicomte De Bragelonne.jpeg",
  "when dimple met rishi": "/BookCoversNew/When Dimple Met Rishi.jpeg",
  "When Only Love Remains   Durjoy Datta": "/BookCoversNew/When ONly Love Remains Durjoy Datta.jpeg",
  "Wilde Oscar Short Stories": "/BookCoversNew/Wilde Oscar Short Stories.jpeg",
  "Wonder": "/BookCoversNew/Wonder.jpeg",
  "अकबर और बरबल": "/BookCoversNew/दो बैलों की कथा.png",
  "01 Henry and Mudge The First Book of Their Adventures 1987": "/BookCoversNew/Henry and Mudge the first book.png",
  "02 Henry and Mudge in Puddle Trouble 1987": "/BookCoversNew/Henry and Mudge in puddle trouble.png",
  "03 Henry and Mudge in the Green Time 1987": "/BookCoversNew/Henry and Mudge in the green time.png",
  "04 Henry and Mudge Under the Yellow Moon 1987": "/BookCoversNew/Henry and Mudge under the yellow moon.png",
  "05 Henry and Mudge in the Sparkle Days 1988": "/BookCoversNew/Henry and Mudge in the sparkle days.png",
  "06 Henry and Mudge and the Forever Sea 1989": "/BookCoversNew/Henry and Mudge and the forever sea.png",
  "08 Henry and Mudge and the Happy Cat 1990": "/BookCoversNew/Henry and Mudge and the happy cat.png",
  "11 Henry and Mudge and the Long Weekend 1992": "/BookCoversNew/Henry and Mudge and the long weekend.png",
  "12Th Fail (Hindi Novel)": "/BookCoversNew/12th Fail.png",
  "12 Henry and Mudge and the Wild Wind 1993": "/BookCoversNew/Henry and Mudge and the wild wind.png",
  "13 Henry and Mudge and the Careful Cousin 1994": "/BookCoversNew/Henry and Mudge and the careful cousin.png",
  "16 Henry and Mudge and the Sneaky Crackers February 1999": "/BookCoversNew/Henry and Mudge and sneaky crackers.png",
  "17 Henry and Mudge and the Starry Night May 1999": "/BookCoversNew/Henry and Mudge and the starry night.png",
  "19 Henry and Mudge and the Snowman Plan October 2000": "/BookCoversNew/Henry And Mudge And The Snowman Plan.png",
  "2 states the story of my marriage by chetan bhagat": "/BookCoversNew/2 States The Story Of My Marriage.png",
  "2015.308704.Saket": "/BookCoversNew/Saket.png",
  "2015.441965.Hast Rekha": "/BookCoversNew/Hast rekha.png",
  "21 Henry and Mudge and the Tall Tree House 2002": "/BookCoversNew/Henry and Mudge and the tall tree house.png",
  "23 Henry and Mudge and the Wild Goose Chase October 2003": "/BookCoversNew/Henry and Mudge and the wild goose.png",
  "25 Henry and Mudge and a Very Merry Christmas October 2004": "/BookCoversNew/Henry and Mudge and a very merry christmas.png",
  "26 Henry and Mudge and the Great Grandpas April 2005": "/BookCoversNew/Henry and Mudge and the great grandpa.png",
  "27 Henry and Mudge and the Tumbling Trip October 2005": "/BookCoversNew/Henry and Mudge and the tumbling trip.png",
  "28 Henry and Mudge and the Big Sleepover May 2007": "/BookCoversNew/Henry and Mudge and a big sleepover.png",
  "A Little Life A Novel (Hanya Yanagihara) (z lib.org).epub": "/BookCoversNew/a little life.jpg",
  "Accidentally in Love  Nikita Singh": "/BookCoversNew/accidentally in love.jpg",
  "Accidental Love   Gary Soto": "/BookCoversNew/Accidental love.png",
  "Adam Nevill   The Ritual": "/BookCoversNew/the ritual.jpg",
  "Advantage Love   Madhuri Banerjee": "/BookCoversNew/advantage love.jpg",
  "An Unexpected Gift By Ajay K Pandey": "/BookCoversNew/An Unexpected Gift.jpg",
  "Ankur Warikoo   Get Epic Shit Done Juggernaut Books (2022)": "/BookCoversNew/get epic shit done.jpg",
  "An Introduction to Buddhism Core Teachings of Dalai Lama Book 3": "/BookCoversNew/An Introduction To Buddhism.jpg",
  "APJ Abdul Kalam with Arun Tiwari Wings of Fire An Autobiography": "/BookCoversNew/Wings of fire.jpg",
  "Ayurveda Treatment for Beginner   Kathleen Hanson": "/BookCoversNew/ayurveda.jpg",
  "Ayurveda The Divine Science": "/BookCoversNew/Ayurveda Divine Science Of Life.jpg",
  "A Half Baked Love Story   Anurag Garg": "/BookCoversNew/a half baked love story.jpg",
  "Can Love Happen Twice    Ravinder Singh freebooksplanet.com": "/BookCoversNew/can love happen twice.jpg",
  "Charitraheen Characterless Novel in Hindi by Sharatchandra Chatt": "/BookCoversNew/charitraheen.jpg",
  "Chetan Bhagat  One Night @ The Call Center": "/BookCoversNew/One night at the call center.png",
  "CORONAVIRUS Osler": "/BookCoversNew/coronavirus.jpg",
  "Crime and Punishment    Fyodor Dostoyevsky": "/BookCoversNew/crime and punishment.jpg",
  "Daniel Goleman  Goleman   Emotional Intelligence)": "/BookCoversNew/Emotional Intelligence.jpg",
  "Danielle Moore, Jason Gray STOP OVERTHINKING 3 Books In 1 Overth": "/BookCoversNew/Stop Overthinking.jpg",
  "David Deida The Way of the Superior Man A Spiritual Guide to Mas": "/BookCoversNew/the way of the superior man.jpg",
  "Dick Lyles Winning Habits 4 Secrets That Will Change the Rest of": "/BookCoversNew/winning habits.jpg",
  "Don t Feed the Monkey Mind How to Stop the Cycle of Anxiety, Fea": "/BookCoversNew/Don T Feed The Monkey Mind.jpg",
  "Do Kadam Aur Sahi Hindi Edition by Rahat Indori z lib org": "/BookCoversNew/rahat indori.jpg",
  "Drawing Cartoons   Comics for Dummies ( PDF)": "/BookCoversNew/drawing cartoons and comics for dummies.jpg",
  "Durjoy Datta   She Broke Up I Didn t": "/BookCoversNew/She Broke Up. I Didn T.jpg",
  "Durjoy Datta   Till The Last Breath": "/BookCoversNew/Till The last breath.png",
  "Durjoy Datta   World s Best Boyfriend": "/BookCoversNew/World S Best Boyfriend.jpg",
  "Durjoy Dutta   HOLD MY HAND": "/BookCoversNew/hold my hand.jpg",
  "Durjoy Dutta   Our IMPossible Love": "/BookCoversNew/our impossible love.jpg",
  "elmers special day by david mckee": "/BookCoversNew/elmers special day.jpg",
  "English Fairy Tales and More English Fairy Tales And, More Engli": "/BookCoversNew/English Fairy tales.png",
  "Feeling Good by David Burns  736": "/BookCoversNew/feeling good.jpg",
  "Few Things Left Unsaid  Sudeep Nagarkar": "/BookCoversNew/few things left unsaid.jpg",
  "Finish What You Start The Art of Following Through, Taking Actio": "/BookCoversNew/Finish what you start.jpg",
  "First We Make the Beast Beautiful   Sarah Wilson  233": "/BookCoversNew/First We Make The Beast Beautiful.jpg",
  "Gamini Singla HOW I TOPPED THE UPSC AND HOW YOU CAN TOO What It": "/BookCoversNew/how I topped the upsc.jpg",
  "Genius Foods Become Smarter, Happier, and More Productive While": "/BookCoversNew/genius foods.jpg",
  "Give and Take  WHY HELPING OTHERS DRIVES OUR SUCCESS ( PDF )": "/BookCoversNew/give and take.jpg",
  "Grandma s Bag of Stories By Sudha Murty": "/BookCoversNew/Grandma S Bag Of Stories.jpg",
  "Half Girlfriend by Chetan Bhagat": "/BookCoversNew/Half Girlfriend.jpg",
  "harry potter 2 chamber of secrets": "/BookCoversNew/The Secret.jpeg",
  "healing the child within  148": "/BookCoversNew/Healing the child within.png",
  "Healing Depression": "/BookCoversNew/healing depression the mind body way.jpg",
  "Hotel by Arthur Hailey": "/BookCoversNew/hotel.jpg",
  "House of Cards A Novel By Sudha Murty": "/BookCoversNew/house of cards.jpg",
  "How to Win Every Argument ( PDF)": "/BookCoversNew/How To Win Every Argument.jpg",
  "How to Read People Like a Book A Guide to Speed Reading People,": "/BookCoversNew/how to read people like a book.jpg",
  "I Too had a Love Story by Ravinder Singh": "/BookCoversNew/i too had love story.jpg",
  "India that is Bharat by J Sai Deepak": "/BookCoversNew/India That Is Bharat.jpg",
  "Inferno by BrownDan": "/BookCoversNew/inferno.jpg",
  "It Happens for A Reason by Preeti Shenoy": "/BookCoversNew/It happens for a reason.jpg",
  "It Started with a Friend Request  Sudeep Nagarkar": "/BookCoversNew/It Started With A Friend Request.jpg",
  "It s Not How Good You Are, It s How Good You Want to Be 132": "/BookCoversNew/It S Not How Good You Are, It S How Good You Want To Be.jpg",
  "J. R. R. Tolkien   Adventures of Tom Bombadil (1978)": "/BookCoversNew/The adventures of Tom bombadil.png",
  "James clear   atomic habits (2022)": "/BookCoversNew/atomic habits.jpg",
  "Jay Shetty Think Like a Monk Train Your Mind for Peace and Purpo": "/BookCoversNew/think like a monk.jpg",
  "Jeff Keller Attitude is Everything International Network Trainin": "/BookCoversNew/Attitude Is Everything.jpg",
  "Julius Caesar  The Colossus of Rome": "/BookCoversNew/the colossus of rome.jpg",
  "Katie In Love full length erotic romance novel by Thurlow, Chloe": "/BookCoversNew/Katie in love.jpg",
  "Lamb, Christina Yousafzai, Malala I am Malala the girl who stood": "/BookCoversNew/I am malala.jpg",
  "Learn German with Stories Karneval in Köln 10 Short Stories for": "/BookCoversNew/Learn German with stories.png",
  "Learn Russian with Beginner Stories Interlinear Russian to Engli": "/BookCoversNew/Learn Russian with beginner stories.png",
  "Legal Eagles Stories of the Top Seven Indian Lawyers by Indu Bha": "/BookCoversNew/legal eagles.jpg",
  "Life Is What You Make It by Preeti Shenoy": "/BookCoversNew/life is what you make it.jpg",
  "Long Walk to Freedom The Autobiography of Nelson Mandela by Nels": "/BookCoversNew/long walk to Freedom.jpg",
  "Love  Kisses And All Things Warm by Preeti Shenoy": "/BookCoversNew/Love Kisses And All Things Warm.jpeg",
  "love@facebook   singh nikita": "/BookCoversNew/Love@facebook.jpeg",
  "Lynn Grabhorn Dear God, What s Happening to Us Halting Eons of M": "/BookCoversNew/Lynn Grabhorn Dear God What S Happening To Us.jpeg",
  "Mahabharat महभरत Hindi Priyadarshi Prakash": "/BookCoversNew/Mahabharat Hindi.jpeg",
  "Mahayoddha Kalki  Sword of Shiva by Kevin Missal": "/BookCoversNew/Mahayoddha Kalki Sword Of Shiva.jpeg",
  "Mary Poppins 1967  Read Along Book": "/BookCoversNew/Mary poppins 1967.jpeg",
  "Mauri Valtonen, Hannu Karttunen The three body problem Cambridge": "/BookCoversNew/Mauri Valtonen Hannu Karttunen.jpeg",
  "Mel Robbins The 5 Second Rule Transform your Life, Work, and Con": "/BookCoversNew/The 5 Second Rule Transform Your Life.jpeg",
  "Mistakes Like Love and Sex   Madhuri Banerjee": "/BookCoversNew/Mistakes Like Love And Sex.jpeg",
  "Modern Arabic Short Stories  A Bilingual Reader": "/BookCoversNew/Modern Arabic Short Stories.jpeg",
  "Moonwalking with Einstein the art and science of remembering eve": "/BookCoversNew/Moonwalking With Einstein.jpeg",
  "Morgan Housel The Psychology of Money Timeless Lessons on Wealth": "/BookCoversNew/Morgan Housel Psychology of Money.jpeg",
  "MY CLINGY GIRLFRIEND   MADHURI BANERJEE": "/BookCoversNew/My Clingy Girlfriend Madhuri.jpeg",
  "Of Course I Love You!  Till I f": "/BookCoversNew/Of Course I Love You Till I Found Someone Better.jpeg",
  "Ohh Yes  I m Single  And so is Datta ": "/BookCoversNew/Ohh Yes I M Single And So Is D.jpeg",
  "One Arranged Murder by Chetan Bhagat": "/BookCoversNew/One Arranged Murder.jpeg",
  "Osho, Osho International Foundation Life is a soap bubble 100 wa": "/BookCoversNew/Osho Osho International Foundation.jpeg",
  "Our Story Needs No Filter   Sudeep Nagarkar": "/BookCoversNew/Our Story Needs No Filter Sudeep.jpeg",
  "Picture Dictionary, Longman Childrens Picture Dictionary by Pear": "/BookCoversNew/Picture Dictionary Longman Children.jpeg",
  "pingpdf.com the girl of my dreams infocopain": "/BookCoversNew/pingpdf.com The girl of my dreams.jpeg",
  "Reasons to Stay Alive by Matt Haig  158": "/BookCoversNew/Reasons To Stay Alive Matt Haig.jpeg",
  "Rich Dads Increase Your Financial IQ Get Smarter with Your Money": "/BookCoversNew/Rich Dads Increase Your Financial IQ.jpeg",
  "Right Here Right Now   NIKITA SINGH NOVEL": "/BookCoversNew/Right Here Right Now Nikita Singh.jpeg",
  "Satyayoddha Kalki  Eye of Brahma by Kevin Missal": "/BookCoversNew/Satyayoddha Kalki Eye Of Brahma.jpeg",
  "Short Stories For Children   ArvindGuptaToys Books Gallery": "/BookCoversNew/Short Stories For Children.jpeg",
  "Short Stories for Children for Spoken English": "/BookCoversNew/Short Stories For Children For Spoken English Practice.jpeg",
  "Sir Arthur Conan Doyle   Complete Sherlock Holmes (1960)": "/BookCoversNew/Sir Arthur Conan Doyle Complete.jpeg",
  "Someone Like You Durjoy  Datta i": "/BookCoversNew/Someone Like You Durjoy Datta.jpeg",
  "Something I Never Told You by Bhinder Shravya @BOOKHOUSE1": "/BookCoversNew/Something I Never Told You.jpeg",
  "Sorry, You are not my Type by Sudeep Nagarkar": "/BookCoversNew/Sorry, You Are Not My Type By Sudeep.jpeg",
  "Stephen W Hawking The theory of everything 2006, Phoenix Books l": "/BookCoversNew/Stephen W Hawking The Theory Of Everything.jpeg",
  "Super Immunity The Essential Nutrition Guide for Boosting Your B": "/BookCoversNew/Super Immunity The Essential Nutrition.jpeg",
  "The 3 (Three) Mistakes of My Life by Chetan Bhagat (z)": "/BookCoversNew/The Mistakes Of My Life.jpeg",
  "The Boy in The Striped Pajamas   D. Boyne": "/BookCoversNew/The Boy In The Striped Pajamas.jpeg",
  "The Gifts of Imperfection  Embrace Who You Are ( PDFDrive )": "/BookCoversNew/The Gifts Of Imperfection.jpeg",
  "The Girl in Room 105 by Chetan Bhagat": "/BookCoversNew/The Girl In Room 105.jpeg",
  "The Jungle Book": "/BookCoversNew/The Jungle Book Rudyard Kipling.jpeg",
  "THE ONE YOU CANNOT HAVE BY PREE   PREETI SHENOY": "/BookCoversNew/The One You Cannot Have.jpeg",
  "The Paradoxical Prime Minister by Shashi Tharoor (z)": "/BookCoversNew/The Paradoxical Prime Minister.jpeg",
  "The Promise by Nikita Singh indianauthornovels.blogspot.in": "/BookCoversNew/The Promise Nikita Singh.jpeg",
  "The Secret wish List   Shenoy  Preeti": "/BookCoversNew/The Secret Wish List.jpeg",
  "The Silent Patient by Alex Michaelides": "/BookCoversNew/The Silent Patient.jpeg",
  "The Wheel of Time by Robert Jordan  Brandon Sanderson (z)": "/BookCoversNew/The Wheel Of Time.jpeg",
  "The Anxiety and Phobia Workbook  614": "/BookCoversNew/The Anxiety And Phobia Workbook.jpeg",
  "The Art of Public Speaking The Original Tool for Improving Publi": "/BookCoversNew/The Art Of Public Speaking.png",
  "The Boy with a Broken Heart   Durjoy Datta": "/BookCoversNew/The Boy With A Broken Heart.jpeg",
  "The Courage to be Disliked How to Change Your Life and Achieve R": "/BookCoversNew/The Courage To Be Disliked.jpeg",
  "The Girl I Last Loved   Smita Kaushik": "/BookCoversNew/The Girl I Last Loved Smita Kau.jpeg",
  "The Happiness Trap  292": "/BookCoversNew/The Happiness Trap.jpeg",
  "The Intelligent Investor The Definitive Book On Value Investing": "/BookCoversNew/The Intelligent Investor.jpeg",
  "The Lord of the Rings  , 2 J R R Tolkien Lord of the Rings, Part": "/BookCoversNew/The Lord Of The Rings 2.jpeg",
  "The Lord of The Rings  , 3 J R R Tolkien Lord of The Rings, Part": "/BookCoversNew/The Lord Of The Rings 3.jpeg",
  "The Man Who Saved India Sardar Patel and His Idea of India by Hi": "/BookCoversNew/The Man Who Saved India SARDAR PATEL.jpeg",
  "The Merry Adventures of Robin Hood NT": "/BookCoversNew/The Merry Adventures Of Robin Hood.jpeg",
  "the mother i never knew Sudha Murthy": "/BookCoversNew/The Mother I Never Knew.jpeg",
  "This Love that Feels Right . . .   Ravinder Singh 2105155939": "/BookCoversNew/This Love That Feels Right.jpeg",
  "Three Mistakes of My Life": "/BookCoversNew/Th 3 (Three) Mistakes Of My Life Chetan Bhagat.jpeg",
  "Three Ghost Stories NT": "/BookCoversNew/Three Ghost Stories.jpeg",
  "Time Stops At Shamli Other Stories   Ruskin Bond": "/BookCoversNew/Time Stops At Shamli.jpeg",
  "Trading Price Action Trading Ranges Technical Analysis of Price": "/BookCoversNew/Trading Price Action Trading Ranges.jpeg",
  "Tyler Volk What Is Death A Scientist Looks at the Cycle of Life": "/BookCoversNew/What Is Death.jpeg",
  "Undergraduate topics in computer science Antti Laaksonen Guide t": "/BookCoversNew/Undergraduate Topics In Computer Science.jpeg",
  "Universal Magick (2021) by Hargrove, Corwin (z)": "/BookCoversNew/Universal Magick.jpeg",
  "Veronika Decides to Die   Paulo Coelho": "/BookCoversNew/Veronika Decides To Die.jpeg",
  "Wabi Sabi Japanese Wisdom for a Perfectly Imperfect Life Beth Ke": "/BookCoversNew/Wabi Sabi Japanese Wisdom For A Perfectly Imperfect Life.jpeg",
  "World s Best Boyfriend Durjoy Da": "/BookCoversNew/World S Best Boyfriend Durjoy Datta.jpeg",
  "Your Dreams Are Mine Now Novel Ravinder Singh in pdf": "/BookCoversNew/Your Dreams Are Mine Now Novel.jpeg",
  "You are the Best Wife  A True Love Story   Ajay Pandey": "/BookCoversNew/You Are The Best Wife.jpeg",
  "You Were My Crush  Till You Sai": "/BookCoversNew/You Were My Crush Till You Said Durjoy Datta.jpeg",
  "गनह क दवत Gunahon Ka Devta by भरत Dharamvir Bharatiz": "/BookCoversNew/Gunahon ka devta.png",
  "07 Henry and Mudge Get the Cold Shivers 1989": "/BookCoversNew/10 ways to write effective ads.png",
  "09 Henry and Mudge and the Bedtime Thumps 1991": "/BookCoversNew/100 Selected Short Stories.jpeg",
  "10 Ways to Write More Effective Ads": "/BookCoversNew/100 years of best American stories.png",
  "100 years of the best American short stories": "/BookCoversNew/5 points someone what not to do at iit.jpg",
  "10 Books in 1 Memory, Speed Read, Note Taking, Essay Writing, Ho": "/BookCoversNew/50 stories in easy english.png",
  "10 Hanry and Mudge Take the Big Test 1991": "/BookCoversNew/A Day In The Life Robert Greenfield.jpeg",
  "15 Henry and Mudge in the Family Trees September 1998": "/BookCoversNew/a textbook of dravyaguna.jpg",
  "18 Henry and Mudge and Annie 39 s Good Move January 2000": "/BookCoversNew/adventures of huckleberry fins.jpg",
  "2015.348947.Gunahon Ka": "/BookCoversNew/Akbar Aur Birbal.jpeg",
  "20 Henry and Mudge and Annie 39 s Perfect Pet February 2001": "/BookCoversNew/american folktales.jpg",
  "22 Henry and Mudge and Mrs Hopper 39 s House February 2003": "/BookCoversNew/Black Hole Physics.jpg",
  "50 stories in englsih": "/BookCoversNew/Buddha S Brain.jpg",
  "6 anurag do bail premchand": "/BookCoversNew/Charlie Chaplin S Biography.png",
  "A Text Book of Dravyaguna Vijnana": "/BookCoversNew/chikitsa sutra.jpg",
  "Adventures of Huckleberry Finn": "/BookCoversNew/ego is the enemy.jpg",
  "Allen B Tucker Computer Science and Engineering Handbook Chapman": "/BookCoversNew/elmers friend.jpg",
  "American Folk Tales": "/BookCoversNew/English through short stories and jokes.png",
  "A P Godse, D A Godse Microprocessors   Microcontroller Systems 2": "/BookCoversNew/Essentials Of Pharmacoeconomics.jpg",
  "Bhagavad Gita (Hindi))": "/BookCoversNew/Frankstein.png",
  "Biograph of Charlie Chaplin": "/BookCoversNew/General Knowledge From The Quaran.jpg",
  "Biography of Swami Vivekananda": "/BookCoversNew/granny and zooey.jpg",
  "Buddhas Brain The Practical Neuroscience of Happiness, Love, and": "/BookCoversNew/Harry Potter And The Chamber Of Secrets.jpg",
  "can love happentwice ebook full": "/BookCoversNew/Harry Potter and the deathly hallows.jpg",
  "chikkitsasutraKC ..ajeet ": "/BookCoversNew/Harry Potter and the goblet of fire.jpg",
  "Durjoy Datta   Of Course I Love You": "/BookCoversNew/Harry Potter and the half blood prince.jpg",
  "Durjoy Datta   You Were My Crush Hindi": "/BookCoversNew/Harry Potter and the prisoner of azkaban.jpg",
  "Durjoy Datta   You Were My Crush": "/BookCoversNew/Harry Potter and the sorcerers stone.jpg",
  "Durjoy Dutta   Now That You re Rich": "/BookCoversNew/Harry Potter Complete Collection.jpg",
  "Durjoy Dutta   Oh Yes I m Single": "/BookCoversNew/Harry Potter special.jpg",
  "Durjoy Dutta   Someone Like You": "/BookCoversNew/harry-potter-1-philosophers-stone.png",
  "Durjoy Dutta   Tell The Last Breath": "/BookCoversNew/harry-potter-2-chamber-of-secrets.png",
  "Ego is the Enenmy by Ryan Holiday (z lib.org)": "/BookCoversNew/harry-potter-3-prisoner-of-azkaban.png",
  "elmer friends": "/BookCoversNew/harry-potter-4-goblet-of-fire.png",
  "englsih through short stories": "/BookCoversNew/harry-potter-5-order-of-phoenix.png",
  "five point someone chetan bhagat ebook": "/BookCoversNew/harry-potter-6-half-blood-prince.png",
  "Frankenstein NT": "/BookCoversNew/harry-potter-7-deathly-hallows.png",
  "Franny and Zooey": "/BookCoversNew/harry-potter-8-cursed-child.png",
  "Fundamental Theories of Physics 96 Valeri P Frolov, Igor D Novik": "/BookCoversNew/Henry And Mudge And Annie S Good Move.png",
  "harry potter 1 philosophers stone": "/BookCoversNew/Henry and Mudge and the bedtime thums.png",
  "harry potter 3 prisoner of azkaban": "/BookCoversNew/Henry and Mudge and the cold shivers.png",
  "harry potter 4 goblet of fire": "/BookCoversNew/Henry And Mudge Annie S Perfect Pet.png",
  "harry potter 5 order of phoenix": "/BookCoversNew/Henry And Mudge Mr Hopper S House.png",
  "harry potter 6 half blood prince": "/BookCoversNew/Henry and Mudge take the big test.png",
  "harry potter 7 deathly hallows": "/BookCoversNew/hold my hand(1).jpg",
  "harry potter 8 cursed child": "/BookCoversNew/How To Analyse People.jpg",
  "Harun Yahya General Knowledge fron the Qur an 2003 libgen lc": "/BookCoversNew/How To Talk To Anyone 92 Trick.jpg",
  "Hold my Hand Penguin Metro Rea Durjoy": "/BookCoversNew/If It S Not Forever, It S Not Love.jpg",
  "How To Analyze People 13 Laws About the Manipulation of the Huma": "/BookCoversNew/images (2).jpeg",
  "I Too Had A Love Story pdf Ravinder Singh": "/BookCoversNew/It S All In The Planets.png",
  "If It s Not Forever Durjoy Datta": "/BookCoversNew/Kanark.png",
  "It Happens for a Reason   Preeti Shenoy": "/BookCoversNew/Long Walk To Freedom The Autobigraphy.jpeg",
  "Its All In The Planets by Preeti Shenoy": "/BookCoversNew/Losing My Virginity And All Other Dares.jpeg",
  "It Started with a Friend Reques": "/BookCoversNew/Mahabharat Ved Vyas.jpeg",
  "Konark Hindi Novel": "/BookCoversNew/Mark Twain The adventures of Tom Swain.jpeg",
  "Leil Lowndes How to Talk to Anyone 92 Little Tricks for Big Succ": "/BookCoversNew/Mel Robbins The 5 Second Rule.jpeg",
  "Lippincott Williams   Wilkins Karen Rascati Essentials of Pharma": "/BookCoversNew/microprocessor and microcontroller system.jpg",
  "Losing My Virginity and Other D   Banerjee  Madhuri": "/BookCoversNew/Napolean A Biography.jpeg",
  "Mahabharata   Veda Vyasa (eng)": "/BookCoversNew/Now That You Re Rich, Let S Fall In Love.jpg",
  "Mark Twain   The adventures of Tom Sawyer": "/BookCoversNew/Oh Yes I M Single, And So Is My Girlfriend.jpg",
  "Napoleon A Biography": "/BookCoversNew/One Hundred Years Of Soltitude.jpeg",
  "one hundred years of solitude": "/BookCoversNew/Paulo Caelho A Warrior S Life.jpeg",
  "One Indian Girl": "/BookCoversNew/Paulo Caelho The Alchemist (1993).jpeg",
  "P M Nair  The Kalam Effect": "/BookCoversNew/Percy Jackson And The Battle Of The Labyrimin.jpeg",
  "Paulo Coelho   The Alchemist (1993)  ": "/BookCoversNew/PM Nair The Kalam Effect.jpeg",
  "Paulo Coelho. A Warrior s Life": "/BookCoversNew/Presentation Secets Of Steve Jobs.jpeg",
  "Percy Jackson and The Battle of the Labyrinth": "/BookCoversNew/Python API Deevelopment Fundamentals.jpeg",
  "Presentation Secrets Of Steve Jobs": "/BookCoversNew/Rattan Lal Ichhpuja Rajesh Bhatia.jpeg",
  "Python API Development Fundamentals Develop a full stack web app": "/BookCoversNew/Reconsidering Redd+ Authority Ananya Sharma.jpeg",
  "Rajesh Bhatia, Rattan Lal Ichhpujani Essentials of Medical Micro": "/BookCoversNew/Scian Of Ikshvaku Ram Chandra.jpeg",
  "Reconsidering REDD+ Authority, Power and Law in the Green Econom": "/BookCoversNew/second edition computer science handbook.jpg",
  "Robert Greenfield A Day in the Life One Family, the Beautiful Pe": "/BookCoversNew/She Broke Up I Didn T I Just Kissed.jpeg",
  "Robin S Sharma The Monk Who Sold His Ferrari A Fable About Fulfi": "/BookCoversNew/She Broke Up I Didn T Just Du.jpeg",
  "Scion of Ikshvaku (Ram Chandra   Amish Tripathi": "/BookCoversNew/Shri Ramcharitramanas (Hindi).jpeg",
  "She Broke Up I Didnt I Just Kissed Someone Else": "/BookCoversNew/sorry you are not my type.jpeg",
  "She Broke Up  I Didn t  I Just Durjoy": "/BookCoversNew/Sri Ramcharitramanas English All Pages.jpeg",
  "SHORT STORIES": "/BookCoversNew/Steal the show for speeches to stage.jpeg",
  "Short stories from 100 Selected Stories 2": "/BookCoversNew/Stories Of Panchatantra.jpeg",
  "Shri Ramcharitmanas   (Hindi)": "/BookCoversNew/STORYCRAFT The Complete Guide to Storytelling.jpeg",
  "sorry youre not my type": "/BookCoversNew/SwadeshiChikitsa Vol 1.jpeg",
  "Sri Ramcharitmanas English All pages": "/BookCoversNew/Swami vivekananda biography.png",
  "Steal the Show From Speeches to Job Interviews to Deal Closing P": "/BookCoversNew/Tea For Two And A Piece Of Cake Sudeep Menon.jpeg",
  "Stories from PANCHATANTRA": "/BookCoversNew/Tejguru Sirshee Tejparkhiji Mukti.jpeg",
  "Storycraft the complete guide to writing narrative nonfiction by": "/BookCoversNew/Ten books in one.png",
  "SwadeshiChikitsa 1": "/BookCoversNew/That S The Way We Meet N.jpeg",
  "Tea for Two and a Piece of Cake   Shenoy  Preeti": "/BookCoversNew/That S The Way We Meet Sudeep Menon.jpeg",
  "Tejguru Sirshree Tejparkhiji Mukti Self Liberation From Fear Wor": "/BookCoversNew/That S The Way We Met Sudeep Menon.jpeg",
  "Thats The Way We Met by N": "/BookCoversNew/The 5 Am Club Robin Sharma.jpeg",
  "Thats The Way We Met   Sudeep Nagarkar": "/BookCoversNew/The Alchemist By Paulo Caelho.jpeg",
  "The 5AM Club by Robin Sharma (z)": "/BookCoversNew/The Count Of Monte Cristo.jpeg",
  "The Alchemist by Paulo Coelho": "/BookCoversNew/The Fisher Queens Dyansty.jpeg",
  "The Count Of MonteCristo": "/BookCoversNew/The Fox Frederick Forysyth.jpeg",
  "The Fox by Frederick Forsyth": "/BookCoversNew/The Lord Of The Rings 1.jpeg",
  "The Three Musketeers": "/BookCoversNew/The Three Musketeres.jpeg",
  "The Fisher Queens Dynasty": "/BookCoversNew/The One You Cannot Have Preti Shenoy.jpeg",
  "The Secret by Rhonda Byrne": "/BookCoversNew/The Road Less Travelled.jpeg",
  "The Worlds Best Boyfriend": "/BookCoversNew/THE THREE MUSKETERS.jpeg",
  "The 5 Second Rule Transform your Life, Work, and Confidence with": "/BookCoversNew/tum meru crush ho.jpg",
  "The Lord of the Rings  , 01 J R R Tolkien The Fellowship of the": "/BookCoversNew/Unn Freedom,Paryavaran And Atma Bharat.jpeg",
  "The One You Cannot Have by Preeti Shenoy": "/BookCoversNew/Very Hungry Cterpillar.jpeg",
  "The Road Less Traveled, 25th Anniversary Edition  381": "/BookCoversNew/Vladmir Nabokov Lolita Penguin Modern Classics.jpeg",
  "Till the Last Breath Durjoy Datt": "/BookCoversNew/When Bad Things Happens To Good People.jpeg",
  "Very Hungry Caterpillar FINAL (1)": "/BookCoversNew/Will You Still Love Me Ravindra Singh.jpeg",
  "Vladimir Nabokov Lolita Penguin Modern Classics 2000 (1)": "/BookCoversNew/You Are Trending In My Dreams Now.jpeg",
  "When Bad Things Happen to Good People  114": "/BookCoversNew/You Are Trending In My Dreams Sudeep.jpeg",
  "When Only Love Remains Durjoy Da": "/BookCoversNew/You Re The Password Of My Life.jpeg",
  "Will You Still Love Me By Ravinder Singh": "/BookCoversNew/You were my crush till you said you love me.jpg",
  "Wings of Fire  An Autobiography of APJ Abdul Kalam": "/BookCoversNew/Your Dreams Are Mine Now Ravindra.jpeg"
};

/**
 * Gets the cover image path for a book title
 * @param title The book title to find a cover for
 * @returns The path to the cover image or a default image if not found
 */
export function getBookCover(title: string): string {
  if (!title) return '/placeholder.svg';
  
  // Try to find an exact match
  if (bookCoverMap[title]) {
    return bookCoverMap[title];
  }
  
  // Try case-insensitive match
  const lowerTitle = title.toLowerCase();
  const key = Object.keys(bookCoverMap).find(k => 
    k.toLowerCase() === lowerTitle
  );
  
  if (key) {
    return bookCoverMap[key];
  }
  
  // Default to placeholder
  return '/placeholder.svg';
}
